/**
 * Banco de la evaluación de Mercancías peligrosas: 60 preguntas de opción
 * múltiple, cuatro opciones, una correcta. Cada intento toma 25 al azar y
 * baraja también las opciones.
 *
 * Reglas del banco:
 *   - Cada pregunta sale de una lección. Sin citas, como el resto del
 *     módulo (la nota de fuentes va en la lección 1), pero cada dato se
 *     comprobó contra el LAR 175 y, cuando la regla es de ahí, contra las
 *     Instrucciones Técnicas. Lo que solo existe en un reglamento nacional se
 *     dice como tal, para que nadie lo estudie como si fuera regional.
 *   - La correcta NO es sistemáticamente la más larga: las distractoras son
 *     errores reales de piloto, escritos con el mismo cuerpo. Se mide en
 *     scripts/ y se mantiene por debajo de un tercio del banco.
 *   - Sin niveles de dificultad en pantalla: no se le anuncia a nadie que la
 *     pregunta que tiene enfrente es «avanzada».
 *   - Las cifras que salen de las Instrucciones Técnicas (no cargadas) no se
 *     preguntan como norma: se pregunta dónde están y qué regla las gobierna.
 */

import { shuffle } from "@/lib/notam"

export interface PreguntaEvaluacionMP {
  id: number
  pregunta: string
  opciones: string[]
  /** Índice en `opciones`. Al barajar se remapea. */
  correcta: number
  explicacion: string
  referencia?: string
  /** Lección del módulo de la que sale. */
  leccion: number
}

export interface PreguntaBarajada extends PreguntaEvaluacionMP {
  shuffledOptions: string[]
  correctIndex: number
}

export const MP_EVALUACION_META = {
  total: 60,
  porIntento: 25,
  puntajePorPregunta: 4,
  aprobacion: 80,
  aviso:
    "Las preguntas salen de los mismos documentos que el módulo y son de elaboración propia, no material oficial de ningún organismo ni autoridad: verifica siempre en el reglamento vigente de tu país.",
}

export const MP_PREGUNTAS: PreguntaEvaluacionMP[] = [
  // ── Nivel 1 ─────────────────────────────────────────────────────────────
  { id: 1, leccion: 1, pregunta: "¿Qué hace que un objeto o sustancia sea mercancía peligrosa?", opciones: ["Que el expedidor la declare como tal en el documento de transporte y la acompañe con la declaración firmada por persona idónea", "Que pueda constituir un riesgo y esté en la lista de las Instrucciones o sea clasificable conforme a ellas", "Que lleve pegada una etiqueta de riesgo de las que definen las Instrucciones", "Que figure como prohibida en aeronaves de pasajeros en las Instrucciones Técnicas"], correcta: 1, explicacion: "La definición tiene dos mitades: riesgo para la salud, la seguridad, los bienes o el medio ambiente, y estar en la lista o ser clasificable conforme a las Instrucciones. La declaración y la etiqueta son consecuencias, no la condición." },
  { id: 2, leccion: 1, pregunta: "¿De dónde sale el reglamento de mercancías peligrosas de tu país?", opciones: ["Del Anexo 18 y el Doc 9284 de la OACI, que el SRVSOP convirtió en el LAR 175 y cada Estado adoptó en su propia norma", "De la Reglamentación sobre Mercancías Peligrosas de la IATA, que los Estados hacen obligatoria", "De un acuerdo entre las aerolíneas de la región, homologado después por las autoridades", "Del Convenio de Chicago directamente, sin normas intermedias"], correcta: 0, explicacion: "La OACI promulgó el Anexo 18 y el Doc 9284; con fundamento en el Anexo 18 el Sistema Regional de Cooperación para la Vigilancia de la Seguridad Operacional elaboró el LAR 175 y lo propuso a sus Estados miembros, y cada Estado publicó el suyo: en Colombia, el RAC 175, por la Resolución 00478 de 2016. La IATA publica su propia reglamentación, pero no es la fuente de la obligación." },
  { id: 3, leccion: 1, pregunta: "Un explotador vuela únicamente rutas internas dentro de su país. ¿Le aplican las Instrucciones Técnicas del Doc 9284?", opciones: ["No: solo en vuelos internacionales", "Solo si transporta carga", "Sí, en vuelo interno o internacional", "Solo si sus OpSpecs lo dicen"], correcta: 2, explicacion: "El reglamento colombiano aplica el Anexo 18 y las Instrucciones Técnicas a matrícula colombiana o extranjera, operador nacional o extranjero, vuelo interno o internacional, siempre que Colombia sea origen, sobrevuelo, escala, tránsito, trasbordo o destino." },
  { id: 4, leccion: 1, pregunta: "En el accidente de ValuJet 592 (1996), ¿cómo viajaban los generadores químicos de oxígeno?", opciones: ["Como carga declarada 5.1, con tapas", "Como material de la compañía, marcados como vacíos y sin tapas", "En la cabina de pasajeros, como equipaje de mano de la tripulación de mantenimiento que los acompañaba", "Como correo aéreo, con declaración"], correcta: 1, explicacion: "Iban como COMAT, marcados «Oxy Canisters, Empty», sin las tapas que impiden la activación y sin embalaje adecuado." },
  { id: 5, leccion: 2, pregunta: "¿Qué condiciones del transporte aéreo nombra la norma como las que el embalaje debe resistir?", opciones: ["Radiación y humedad", "Temperatura, humedad, presión y vibración", "Golpes y caídas", "Fuego y agua"], correcta: 1, explicacion: "El reglamento exige embalajes de buena calidad, construidos y cerrados de modo seguro para evitar pérdidas por cambios de temperatura, humedad o presión, o por la vibración." },
  { id: 6, leccion: 3, pregunta: "¿Qué es COMAT?", opciones: ["Carga consolidada de varios expedidores en un mismo sobre-embalaje", "Mercancía peligrosa en cantidades exceptuadas que viaja como carga", "Propiedad del explotador transportada en su propio provecho", "Equipaje excedente de los pasajeros consignado como carga"], correcta: 2, explicacion: "COMAT es la propiedad transportada en una aeronave del explotador en su propio provecho, que no es requisito de operación ni de aeronavegabilidad para ese vuelo; si está clasificada como mercancía peligrosa, es COMAT peligroso." },
  { id: 7, leccion: 3, pregunta: "Las Instrucciones Técnicas no prevén aprobación para un caso concreto. ¿Qué puede pedir el explotador?", opciones: ["Una dispensa", "Una excepción", "Un permiso", "Nada: queda prohibido"], correcta: 0, explicacion: "La norma lo dice tal cual: si no hay referencia específica en las Instrucciones para otorgar una aprobación, se puede pedir una dispensa." },
  { id: 8, leccion: 3, pregunta: "¿Quién otorga las dispensas?", opciones: ["El explotador, en su manual de operaciones, previa notificación a la autoridad y a la OACI", "La autoridad de aviación civil del Estado que corresponda", "El organismo nuclear del país", "La OACI"], correcta: 1, explicacion: "La dispensa es toda autorización distinta de la aprobación, otorgada por la autoridad nacional que corresponda, que exime de lo previsto en las Instrucciones Técnicas. Qué oficina la firma dentro de esa autoridad lo dice cada reglamento: en Colombia, la Secretaría de Seguridad Aérea de la UAEAC." },
  { id: 9, leccion: 3, pregunta: "¿Qué es una excepción, en el sentido del reglamento?", opciones: ["Un permiso que se pide a la autoridad para un envío de extrema urgencia, cuando otro modo de transporte no es apropiado", "Una disposición de la norma que excluye a un artículo de sus condiciones normales", "La autorización del explotador para llevar mercancías peligrosas en cabina", "Una discrepancia notificada por un Estado y publicada en las Instrucciones"], correcta: 1, explicacion: "La excepción no se pide: ya está escrita en la norma. Ejemplo: lo que la aeronave lleva por exigencia de aeronavegabilidad u operación." },
  { id: 10, leccion: 4, pregunta: "¿Quién es responsable de la identificación y clasificación de las mercancías peligrosas?", opciones: ["El explotador", "El agente de carga", "El piloto al mando", "El expedidor"], correcta: 3, explicacion: "El reglamento es explícito: el expedidor es responsable de la identificación y clasificación. Eso no exime al explotador de inspeccionar antes de aceptar." },
  { id: 11, leccion: 4, pregunta: "¿Qué necesita un explotador para poder aceptar y transportar mercancías peligrosas?", opciones: ["Autorización de la autoridad en sus OpSpecs", "Un manual de mercancías peligrosas firmado por el expedidor y aprobado por la autoridad", "La aprobación del comandante", "Tener las Instrucciones Técnicas a bordo"], correcta: 0, explicacion: "Hace falta la autorización en las OpSpecs o documento equivalente, y el reglamento lo repite entre las obligaciones del explotador: solo así puede aceptar y transportar." },
  { id: 12, leccion: 4, pregunta: "Un tercero realiza una función del reglamento en nombre del explotador. ¿Cómo responde?", opciones: ["No responde: la obligación es exclusiva del explotador que lo contrató", "Responde solo si existe un contrato escrito registrado ante la autoridad", "Debe cumplir el reglamento y las Instrucciones igual que el explotador", "Responde ante la OACI y no ante la autoridad de su país"], correcta: 2, explicacion: "Quien realiza una función en nombre del expedidor, del explotador o del operador de terminal tiene que hacerlo conforme al reglamento y a las Instrucciones. El incumplimiento da lugar a acciones administrativas conforme a la legislación de cada país." },
  { id: 13, leccion: 4, pregunta: "¿Cuánto tiempo debe conservar el explotador la copia del documento de transporte de mercancías peligrosas?", opciones: ["Tres meses", "Seis meses", "Dieciocho meses", "Cinco años"], correcta: 0, explicacion: "El LAR pide un mínimo de tres meses, igual que al operador de terminal de carga. Ojo, que aquí los reglamentos nacionales se separan: el de Colombia exige 18 meses al expedidor y al explotador. Cuando te pregunten un plazo, di el de tu reglamento y sabe que no es el mismo en todas partes." },

  // ── Nivel 2 ─────────────────────────────────────────────────────────────
  { id: 14, leccion: 5, pregunta: "Una sustancia es inflamable y corrosiva a la vez. ¿En cuántas clases se incluye?", opciones: ["En dos clases, con un número ONU distinto para cada uno de los dos riesgos", "En una sola: la del peligro más importante", "En ninguna: se prohíbe", "En la clase 9"], correcta: 1, explicacion: "Se incluye en una de las nueve clases según el peligro o el más importante de los peligros que represente. El riesgo restante se refleja en el etiquetado como secundario." },
  { id: 15, leccion: 5, pregunta: "¿Qué es la división 2.1?", opciones: ["Una clase aparte para los líquidos inflamables de bajo punto de inflamación", "Los gases inflamables, dentro de la clase 2", "El grupo de embalaje de los gases", "Los gases tóxicos"], correcta: 1, explicacion: "La clase 2 son los gases; la división 2.1, los inflamables; la 2.2, los no inflamables y no tóxicos; la 2.3, los tóxicos. Decir «clase 2.1» confunde clase con división." },
  { id: 16, leccion: 5, pregunta: "¿Qué distingue a la división 4.3?", opciones: ["Se inflama con facilidad o provoca incendios por fricción durante el transporte", "Se calienta sola con el aire", "Desprende gases inflamables en contacto con el agua", "Libera oxígeno"], correcta: 2, explicacion: "La 4.3 son sustancias que en contacto con el agua desprenden gases inflamables. Por eso el agua no es la respuesta ante un incidente con ellas." },
  { id: 17, leccion: 5, pregunta: "¿En qué clase está el hielo seco?", opciones: ["Clase 2", "Clase 9", "Clase 6", "No es peligrosa"], correcta: 1, explicacion: "El dióxido de carbono sólido figura en el reglamento como ejemplo de sustancia de la clase 9. Sublima y desplaza el oxígeno en un espacio cerrado." },
  { id: 18, leccion: 5, pregunta: "¿Cuál es el criterio de la clase 3?", opciones: ["Vapores inflamables a no más de 60,5 °C en crisol cerrado", "Punto de ebullición inferior a 35 °C a presión atmosférica", "Cualquier líquido que arda al acercarle una llama abierta", "Líquidos que reaccionan con el agua produciendo gases"], correcta: 0, explicacion: "El punto de inflamación: 60,5 °C en crisol cerrado o 65,6 °C en crisol abierto. Pinturas, barnices y lacas son el ejemplo que da la norma." },
  { id: 19, leccion: 5, pregunta: "¿Qué valor define el material magnetizado como clase 9?", opciones: ["Campo de 0,159 A/m a 2,1 m del bulto", "Campo de 2,1 A/m a 0,159 m", "Cualquier imán permanente, sin importar la intensidad del campo que genere", "Campo medido a 10 m"], correcta: 0, explicacion: "Material magnetizado: el que al embalarlo tiene un campo magnético mínimo de 0,159 A/m a una distancia de 2,1 m de cualquier punto de la superficie del bulto." },
  { id: 20, leccion: 6, pregunta: "¿Qué debe llevar marcado todo bulto de mercancías peligrosas, salvo que las Instrucciones digan otra cosa?", opciones: ["El nombre comercial del producto y el peso bruto del bulto", "La denominación del artículo expedido y el número ONU", "El código ERG y la posición de estiba asignada en la bodega", "El nombre del comandante y el número del vuelo"], correcta: 1, explicacion: "Todo bulto irá marcado con la denominación del artículo expedido y con el número de la ONU, más las marcas que especifiquen las Instrucciones." },
  { id: 21, leccion: 6, pregunta: "Un envío de mercancías peligrosas sale de tu país hacia el extranjero. ¿En qué idioma van las marcas?", opciones: ["Solo en el idioma que exija el Estado de origen", "En los idiomas que exija el Estado de origen y, además, en inglés", "El que elija el expedidor", "Solo en inglés"], correcta: 1, explicacion: "En transporte internacional, además de los idiomas exigidos por el Estado de origen, deberá utilizarse el inglés. En vuelo doméstico manda lo que pida tu Estado: Brasil, por ejemplo, exige portugués en todo el transporte interior (discrepancia BR 6)." },
  { id: 22, leccion: 6, pregunta: "¿Cuál es la diferencia entre una etiqueta de riesgo y una de manipulación?", opciones: ["La de riesgo la pone el explotador y la de manipulación el expedidor", "La de riesgo es obligatoria y la de manipulación es opcional", "La de riesgo dice qué es; la de manipulación, cómo se trata", "Son la misma etiqueta con dos nombres según la edición"], correcta: 2, explicacion: "Las de riesgo se requieren para la mayoría de las mercancías de todas las clases; las de manipulación, para algunas, e indican cómo tratar el bulto." },
  { id: 23, leccion: 6, pregunta: "Un bulto llega con la etiqueta de riesgo despegada y no hay certeza de cuál le corresponde. ¿Qué se hace?", opciones: ["Va sin etiqueta", "Se pega la más probable", "No se transporta", "Decide el comandante"], correcta: 2, explicacion: "El explotador repone etiquetas conforme al documento de transporte; pero si no se tiene la certeza de cuál corresponde, no se transporta la mercancía." },
  { id: 24, leccion: 6, pregunta: "¿Qué colores tiene la etiqueta de la división 4.1, sólido inflamable?", opciones: ["Fondo rojo con la llama en blanco, como la clase 3", "Fondo blanco con siete franjas rojas verticales", "Mitad superior blanca y mitad inferior roja, llama en negro", "Fondo azul con la llama en negro o en blanco"], correcta: 1, explicacion: "La 4.1 es blanca con siete franjas rojas verticales; la 4.2, blanca arriba y roja abajo; la 4.3, azul; la clase 3, roja." },
  { id: 25, leccion: 7, pregunta: "¿Qué gradúa el grupo de embalaje?", opciones: ["La clase de la mercancía, del 1 al 9", "El grado de peligro dentro de la clase", "El tamaño y el peso máximo del bulto", "La categoría del material radiactivo"], correcta: 1, explicacion: "Para los fines de embalaje, las sustancias se asignan a tres grupos según el grado de peligro que representan: I gran peligro, II intermedio, III escaso." },
  { id: 26, leccion: 7, pregunta: "¿A cuáles NO se asigna grupo de embalaje?", opciones: ["A las clases 3 y 8, que se gradúan por punto de inflamación", "A las divisiones 5.1 y 6.1, que van por su toxicidad", "A las clases 1, 2 y 7 y a las divisiones 5.2 y 6.2", "A la clase 9 en todos los casos, sin excepción"], correcta: 2, explicacion: "Se excluyen expresamente esas clases y divisiones, y las sustancias de reacción espontánea de la 4.1. Las baterías de litio (clase 9) tampoco lo llevan." },
  { id: 27, leccion: 7, pregunta: "La lista de mercancías peligrosas trae «E0» para un artículo. ¿Qué significa?", opciones: ["Que puede ir en cantidades exceptuadas sin límite de bultos por envío", "Que no puede ir en cantidades exceptuadas", "Que está exento del reglamento", "Que solo va en carguero"], correcta: 1, explicacion: "Salvo disposición contraria en las Instrucciones, las mercancías con la sigla E0 en la lista no pueden ser transportadas en cantidades exceptuadas." },
  { id: 28, leccion: 7, pregunta: "¿Pueden ir las mercancías peligrosas en cantidades exceptuadas como equipaje de mano?", opciones: ["Sí, si va marcada", "Sí, hasta 100 mL", "Solo con aprobación del explotador", "No: ni en equipaje ni en correo"], correcta: 3, explicacion: "La regla es tajante: las cantidades exceptuadas no están permitidas ni como equipaje de mano o facturado, ni como correo." },
  { id: 29, leccion: 7, pregunta: "¿Cómo se identifican en la lista las mercancías que pueden ir en cantidades limitadas?", opciones: ["Con la sigla E0", "Con la instrucción de embalaje «Y»", "Con la palabra «Prohibido»", "Con la etiqueta de manipulación de baterías de litio"], correcta: 1, explicacion: "Las mercancías que incluyen en la lista la instrucción de embalaje «Y» podrán transportarse en cantidades limitadas conforme a esa instrucción." },
  { id: 30, leccion: 8, pregunta: "¿En qué clase están las baterías de ion litio y qué grupo de embalaje llevan?", opciones: ["Clase 3, grupo II", "Clase 8, sin grupo", "Clase 9, sin grupo de embalaje", "Clase 2, grupo III"], correcta: 2, explicacion: "Riesgo eléctrico y térmico que no cubre ninguna otra clase: clase 9. Y no llevan grupo de embalaje; lo que manda es la instrucción de embalaje y el estado de carga." },
  { id: 31, leccion: 8, pregunta: "La norma permite a la autoridad dar una aprobación específica a un explotador sin autorización general, para mercancías de riesgo menor. ¿Cuáles nombra?", opciones: ["Explosivos de la división 1.4 y gases de la división 2.2 sin riesgo secundario, siempre que vayan en cantidades limitadas con instrucción «Y»", "Biológicas Categoría B, litio de la Sección II, COMAT peligroso y lo permitido por correo", "Cualquier mercancía peligrosa embalada en cantidades limitadas con instrucción «Y»", "Material radiactivo de Categoría I-Blanca con índice de transporte cero"], correcta: 1, explicacion: "Son las cuatro que nombra la norma, siempre que el explotador tenga los procedimientos y la instrucción adecuados." },
  { id: 32, leccion: 8, pregunta: "Un teléfono en fuga térmica ya no tiene llama. ¿Por qué la práctica de la industria sigue enfriándolo con agua?", opciones: ["Para limpiar el humo", "Porque la reacción sigue y se propaga por calor", "Porque el agua neutraliza químicamente el litio metálico de las celdas y detiene la reacción", "Porque el halón está prohibido"], correcta: 1, explicacion: "La fuga térmica se alimenta sola y se propaga por calor a las celdas vecinas. Apagar la llama no la detiene; enfriar sí. Por eso no se cubre ni se mueve hasta que esté fría." },
  { id: 33, leccion: 8, pregunta: "¿Qué dice la norma sobre los avisos en los puntos de aceptación de carga?", opciones: ["Que deben estar redactados únicamente en inglés", "Que incluyen ejemplos visuales, comprendidas las baterías", "Que los coloca y mantiene la autoridad en cada aeródromo", "Que son opcionales para quien no acepta mercancías peligrosas"], correcta: 1, explicacion: "El explotador o su agente instala letreros destacados en los puntos de aceptación con ejemplos visuales de las mercancías peligrosas, comprendidas las baterías." },

  // ── Nivel 3 ─────────────────────────────────────────────────────────────
  { id: 34, leccion: 9, pregunta: "Un artículo no aparece en la lista, pero en las condiciones normales de transporte produce llamas. ¿Puede volar?", opciones: ["Sí, porque no está nombrado en la lista de mercancías peligrosas de las Instrucciones Técnicas", "Solo con dispensa", "No: lo prohíbe el criterio material", "Sí, pero solo en carguero"], correcta: 2, explicacion: "En ningún caso se transportan artículos que en las condiciones habituales del transporte puedan explotar, reaccionar peligrosamente, producir llamas o calor o emitir vapores peligrosos. La lista no es exhaustiva." },
  { id: 35, leccion: 9, pregunta: "¿Qué nivel de permiso aplica a los animales vivos infectados?", opciones: ["Permitido sin más", "Prohibido salvo dispensa", "Prohibido en todos los casos", "Permitido solo por correo"], correcta: 1, explicacion: "El reglamento los nombra expresamente: los animales vivos infectados estarán prohibidos salvo dispensa de la autoridad." },
  { id: 36, leccion: 9, pregunta: "¿Qué indica la palabra «Prohibido» en las columnas 2 y 3 de la lista de mercancías peligrosas?", opciones: ["Prohibido solo en pasajeros", "Prohibido salvo dispensa", "Prohibido en todos los casos", "Prohibido solo en Colombia"], correcta: 2, explicacion: "Las mercancías prohibidas cualesquiera que sean las circunstancias van con «Prohibido» en las columnas 2 y 3; las prohibidas en circunstancias normales, en las columnas de pasajeros o de carga." },
  { id: 37, leccion: 10, pregunta: "¿Qué dice el reglamento colombiano sobre las mercancías peligrosas en la aviación civil privada?", opciones: ["Con aprobación", "Solo en cantidades limitadas", "Se prohíben todas", "Solo en helicópteros"], correcta: 2, explicacion: "Por razones de seguridad se prohíbe el transporte de todo tipo de mercancías peligrosas en aeronaves clasificadas dentro de la aviación civil privada." },
  { id: 38, leccion: 10, pregunta: "Operas un monomotor y te piden llevar carga de la clase 8. ¿Qué necesitas?", opciones: ["Nada especial: la clase 8 no está restringida en monomotores ni en la aviación civil privada", "Aprobación de la autoridad, previa verificación de las condiciones de seguridad", "Una dispensa del Estado de destino y del Estado de origen", "Nada: está prohibido en todos los casos, como la clase 3"], correcta: 1, explicacion: "Lo prohibido en monomotor es la clase 3 combustibles. Las demás clases requieren aprobación de la autoridad, que además determina los aeródromos donde no aprueba esa operación." },
  { id: 39, leccion: 10, pregunta: "¿Qué mercancías peligrosas admite el correo aéreo en Colombia?", opciones: ["Ninguna, sin excepción, por la limitación general del correo aéreo", "Muestras de pacientes, infecciosas con hielo seco y radiactivo de muy baja actividad", "Las mismas que en carga, si el operador postal designado las acepta con su manual y su programa de instrucción aprobados", "Solo baterías de litio instaladas en equipos y en cantidades limitadas"], correcta: 1, explicacion: "Son las tres excepciones que admite la norma, a reserva de las autoridades postales y la UPU. El explotador necesita además la autorización en sus OpSpecs." },
  { id: 40, leccion: 10, pregunta: "Un expedidor entrega material radiactivo en Colombia. ¿Qué documento adicional presenta al explotador?", opciones: ["Una dispensa de la autoridad", "La autorización del Servicio Geológico Colombiano", "Un certificado de la OIEA sobre el diseño del bulto y la actividad total del envío", "Nada adicional"], correcta: 1, explicacion: "Cuando se trate de transportar material radiactivo, el expedidor presenta al explotador la autorización del Servicio Geológico Colombiano, Grupo de Seguridad Nuclear y Protección Radiológica." },
  { id: 41, leccion: 10, pregunta: "Según la discrepancia BR 6, ¿en qué idioma van las marcas en el transporte interior de Brasil?", opciones: ["En inglés", "En portugués", "En español", "El del explotador"], correcta: 1, explicacion: "Para todo el transporte del interior en territorio brasileño debe utilizarse el portugués en todas las marcas y documentos; para el internacional con origen en Brasil, además el inglés." },
  { id: 42, leccion: 10, pregunta: "¿Qué debe hacer el expedidor antes de entregar mercancías peligrosas respecto a las discrepancias de los Estados?", opciones: ["Nada: las discrepancias son responsabilidad exclusiva del explotador", "Observar las de cada Estado involucrado y las del explotador", "Pedir una dispensa a cada Estado de tránsito y de destino", "Consultar únicamente las discrepancias notificadas por Colombia"], correcta: 1, explicacion: "El expedidor observa las diferencias de cada Estado involucrado en el transporte y las notificadas por el explotador al que va a entregar la mercancía." },
  { id: 43, leccion: 11, pregunta: "¿Cuál es la regla general para las mercancías peligrosas en el equipaje de pasajeros y tripulantes?", opciones: ["Permitidas en el equipaje facturado y prohibidas en el de mano", "Prohibidas, salvo lo que admiten las Instrucciones Técnicas", "Permitidas hasta 5 kg por persona con aviso en el mostrador", "Permitidas para los tripulantes y prohibidas para los pasajeros"], correcta: 1, explicacion: "Prohibición general en equipaje facturado, de mano y en la persona, con la única excepción de lo que admiten las Instrucciones Técnicas y cumpliendo todos sus requisitos. Los tripulantes tienen la misma regla." },
  { id: 44, leccion: 11, pregunta: "Un pasajero compra su billete por internet. ¿Qué exige la norma sobre las mercancías peligrosas?", opciones: ["Que se le envíe la lista de prohibidos por correo después de la compra", "Que la compra no se complete sin su confirmación de haber entendido", "Nada en ese momento: la información se le da en el mostrador", "Que firme una declaración impresa antes de embarcar"], correcta: 1, explicacion: "En el punto de compra la información puede ir en texto o ilustración, pero el procedimiento debe ser tal que la compra no pueda completarse sin que el pasajero indique que comprendió las restricciones." },
  { id: 45, leccion: 11, pregunta: "En la recepción del equipaje, ¿qué debe obtener el personal del pasajero?", opciones: ["Solo su confirmación verbal de que no lleva mercancías no permitidas, registrada por el agente en el sistema de despacho", "Confirmación de que no lleva no permitidas y del contenido de lo sospechoso", "Una copia firmada de la declaración del expedidor por cada maleta", "Nada: la revisión corresponde al control de seguridad del aeródromo"], correcta: 1, explicacion: "Dos confirmaciones: que no lleva mercancías no permitidas y, ante cualquier artículo que haga sospechar, qué contiene." },
  { id: 46, leccion: 12, pregunta: "¿Qué es una mercancía peligrosa oculta?", opciones: ["Una mercancía estibada en una posición inaccesible durante el vuelo", "Carga con descripción general que debió declararse como peligrosa", "Una mercancía cuya etiqueta de riesgo se despegó en la rampa", "Un envío en cantidades exceptuadas que viaja sin la etiqueta de 100 mm"], correcta: 1, explicacion: "También lo es la mercancía prohibida o en exceso en el equipaje, en la persona o en el correo. «Oxy Canisters, Empty» en ValuJet es el ejemplo clásico." },
  { id: 47, leccion: 12, pregunta: "¿Qué información debe tener a mano el personal de reservas, ventas y recepción de carga y pasajeros?", opciones: ["El precio del transporte de mercancías peligrosas por kilogramo y destino", "Descripciones generales sospechosas, otras indicaciones y lo permitido al pasajero", "El listado completo de sanciones y sus cuantías vigentes, para informar al expedidor en el momento de la aceptación", "Los teléfonos de la OACI y de la Unión Postal Universal para consultas"], correcta: 1, explicacion: "Son las tres cosas que exige la norma: descripciones generales que pueden esconder mercancías peligrosas, otras indicaciones (etiquetas, marcas) y lo que el pasajero sí puede llevar." },

  // ── Nivel 4 ─────────────────────────────────────────────────────────────
  { id: 48, leccion: 13, pregunta: "¿Cuáles son las dos condiciones acumulativas para aceptar mercancías peligrosas?", opciones: ["Que el expedidor sea conocido y que pague el flete por adelantado", "Documento de transporte diligenciado e inspección del bulto", "Que el comandante lo autorice y que el bulto pese menos de 30 kg", "Que lleve etiqueta de riesgo y que viaje dentro de un ULD cerrado"], correcta: 1, explicacion: "Ningún explotador acepta mercancías peligrosas a menos que vayan con documento de transporte diligenciado y hasta que haya inspeccionado el bulto conforme a las Instrucciones. Con lista de verificación." },
  { id: 49, leccion: 13, pregunta: "¿Dónde no se estiban nunca mercancías peligrosas, salvo lo que el reglamento y las Instrucciones permitan?", opciones: ["En la bodega delantera de las aeronaves de fuselaje angosto", "Dentro de un dispositivo de carga unitarizada cerrado", "En la cabina ocupada por pasajeros ni en el puesto de pilotaje", "En aeronaves exclusivamente de carga sin tripulación de cabina"], correcta: 2, explicacion: "Es la primera prohibición de estiba que fija la norma: nada en la cabina ocupada por pasajeros ni en el puesto de pilotaje." },
  { id: 50, leccion: 13, pregunta: "En un carguero, ¿cómo deben cargarse los bultos «Exclusivamente en aeronaves de carga»?", opciones: ["Lo más lejos posible de la cabina de mando y de las salidas", "Donde un tripulante pueda verlos, manipularlos y separarlos en vuelo", "En la bodega inferior, sin acceso, para aislar cualquier fuga", "Junto al material radiactivo, en la zona de segregación"], correcta: 1, explicacion: "Es la lección de South African 295: un bulto al que no se puede llegar es un bulto sobre el que no se puede hacer nada." },
  { id: 51, leccion: 13, pregunta: "¿De qué deben quedar separados los bultos de materiales radiactivos al estibarlos?", opciones: ["De los líquidos inflamables de la clase 3 y de los comburentes de la clase 5, en compartimentos distintos", "De las personas, los animales vivos y las películas no reveladas", "Únicamente de los explosivos de la clase 1", "De la cabina de mando y de los equipos de navegación"], correcta: 1, explicacion: "Los bultos de materiales radiactivos se estiban separados de las personas, los animales vivos y las películas no reveladas, conforme a las Instrucciones." },
  { id: 52, leccion: 13, pregunta: "Al descargar se detecta un bulto con pérdidas. ¿Qué exige el reglamento además de retirarlo?", opciones: ["Anotarlo en la bitácora de mantenimiento y continuar la operación sin más trámite", "Esperar al expedidor", "Inspeccionar la zona de estiba y eliminar la contaminación", "Devolver el envío al origen"], correcta: 2, explicacion: "Se inspecciona la zona donde iba estibado, el explotador comprueba que el resto del envío está bien y que ningún otro bulto quedó contaminado, y elimina la contaminación sin demora." },
  { id: 53, leccion: 14, pregunta: "¿Cuándo debe firmar el piloto al mando la información escrita sobre las mercancías peligrosas?", opciones: ["Al cierre de puertas, junto con el resto de la documentación del vuelo", "Antes de que las mercancías sean transportadas", "En crucero", "Al llegar al destino"], correcta: 1, explicacion: "La información por escrito deberá ser firmada por el piloto al mando antes de que las mercancías sean transportadas." },
  { id: 54, leccion: 14, pregunta: "Vuelo internacional con mercancías peligrosas. ¿En qué idioma va la información al piloto al mando?", opciones: ["Solo en el idioma exigido por el Estado de origen del vuelo, sin traducción", "Solo en inglés", "En los idiomas del Estado de origen y, además, en inglés", "En el idioma del Estado de destino"], correcta: 2, explicacion: "En el transporte internacional, además de los idiomas exigidos por el Estado de origen, deberá utilizarse el inglés. La misma regla aplica a las marcas." },
  { id: 55, leccion: 14, pregunta: "¿Dónde debe estar la información al piloto al mando durante el vuelo?", opciones: ["En la oficina de despacho", "Al alcance del piloto al mando", "En el aeródromo de destino", "Con el agente de rampa"], correcta: 1, explicacion: "La información prevista deberá estar al alcance del piloto al mando durante el vuelo; además, a disposición del aeródromo de última salida y del de próxima llegada, y el explotador conserva copia en tierra." },
  { id: 56, leccion: 15, pregunta: "¿Cuál es el contenido mínimo del equipo de respuesta de emergencia para mercancías peligrosas a bordo?", opciones: ["Extintor de halón, máscara antihumo y guantes ignífugos", "La guía de respuesta de emergencia impresa, el NOTOC y la lista de verificación", "Bolsas grandes de polietileno, ligaduras y guantes largos de goma", "Un kit de primeros auxilios y una manta ignífuga"], correcta: 2, explicacion: "Es literal. El explotador da además instrucción a los tripulantes sobre su uso." },
  { id: 57, leccion: 15, pregunta: "En una emergencia en vuelo con mercancías peligrosas, ¿a quién informa el piloto al mando y cuándo?", opciones: ["Al expedidor, de inmediato, para que confirme el contenido y la posición del envío", "Al ATS, tan pronto la situación lo permita", "A los bomberos de destino", "A la autoridad, antes de aterrizar"], correcta: 1, explicacion: "La cadena es: comandante → ATS → administración aeroportuaria. «Tan pronto la situación lo permita» porque primero se controla la aeronave." },
  { id: 58, leccion: 15, pregunta: "¿De qué documento puede obtenerse la información de respuesta de emergencia que debe estar a disposición del piloto al mando?", opciones: ["El programa de instrucción sobre mercancías peligrosas de la OACI", "Las Instrucciones Técnicas, en su parte de pasajeros y tripulantes", "La guía de respuesta de emergencia de la OACI", "El anexo de la OACI sobre operación de aeronaves"], correcta: 2, explicacion: "Puede obtenerse de la guía de respuesta de emergencia de la OACI o de cualquier otro documento con información equivalente y apropiada respecto a las mercancías a bordo." },
  { id: 59, leccion: 16, pregunta: "Un bulto voló sin la segregación exigida y no pasó nada. ¿Qué es y qué se hace?", opciones: ["Nada: sin daño ni lesiones no hay suceso que notificar a la autoridad", "Un accidente imputable", "Un incumplimiento imputable: se notifica", "Un incidente grave"], correcta: 2, explicacion: "Una ocurrencia atribuible al transporte que no produce incidente ni accidente es un incumplimiento imputable, y hay obligación de notificar lo transportado sin segregar correctamente." },
  { id: 60, leccion: 16, pregunta: "¿Para qué recopila la autoridad datos sobre eventos con mercancías peligrosas que no constituyen accidente ni incidente?", opciones: ["Para calcular las sanciones que correspondan a cada explotador", "Para procesos predictivos y proactivos del SMS", "Para estadísticas ante la OACI", "Para cobrar tasas"], correcta: 1, explicacion: "Es la conexión directa entre mercancías peligrosas y el SMS: el transporte de mercancías peligrosas entra en el ámbito del SMS del explotador y la autoridad recopila hasta lo que no llega a incidente." },
]

// La cuenta y la numeración las comprueba el propio módulo: un banco de 59
// o con dos ids iguales es un error de edición, no una variante.
if (MP_PREGUNTAS.length !== MP_EVALUACION_META.total) {
  throw new Error(`mercanciasEvaluacion: hay ${MP_PREGUNTAS.length} preguntas y el banco declara ${MP_EVALUACION_META.total}`)
}
MP_PREGUNTAS.forEach((q, i) => {
  if (q.id !== i + 1) throw new Error(`mercanciasEvaluacion: la pregunta ${q.id} está en la posición ${i + 1}`)
  if (q.correcta < 0 || q.correcta >= q.opciones.length) throw new Error(`mercanciasEvaluacion: la pregunta ${q.id} tiene una correcta fuera de rango`)
})

/** Prepara un intento: baraja las preguntas, toma `count` y baraja las opciones remapeando la correcta. */
export function buildMercanciasExam(count = MP_EVALUACION_META.porIntento, seed?: number): PreguntaBarajada[] {
  const picked = shuffle(MP_PREGUNTAS, seed).slice(0, count)
  return picked.map((q, qi) => {
    const correctText = q.opciones[q.correcta]
    const shuffledOptions = shuffle(q.opciones, seed ? seed + qi + 1 : undefined)
    return { ...q, shuffledOptions, correctIndex: shuffledOptions.indexOf(correctText) }
  })
}
