-- ============================================================================
-- Autorización de tratamiento con constancia, consentimiento aparte para el
-- certificado médico, y eliminación de la cuenta desde el perfil.
--
-- Viene de la auditoría de prelanzamiento del 26-sep-2026:
--   · La Ley 1581 y el Decreto 1377 piden poder PROBAR la autorización, y para
--     un dato sensible (el certificado médico es un dato de salud) pedirla de
--     forma explícita. Hasta hoy el registro solo decía «al crear tu cuenta
--     aceptas…» y no quedaba nada guardado.
--   · La política promete eliminar la cuenta y no había cómo. El borrado manual
--     dejaba el registro de acceso al banco (sin llave foránea) y fallaba si la
--     cuenta había revisado horas o cargado preguntas.
--
-- Qué hace:
--   1. Tabla autorizaciones (quién aceptó qué documento, en qué versión y
--      cuándo). El piloto la lee; escribe solo registrar_autorizacion().
--   2. Un disparador en licenses_held: un certificado médico no se guarda sin la
--      autorización de dato sensible.
--   3. eliminar_mi_cuenta('ELIMINAR'): borra la cuenta del que llama y, en
--      cascada, todo lo suyo. Los archivos de Storage los borra antes la app
--      por la API de Storage (Supabase no deja borrarlos con SQL); para eso el
--      piloto necesita poder borrar sus archivos de bitácora, y hasta hoy no
--      había política de DELETE en ese bucket.
--   4. revisado_por e inserted_by pasan a «on delete set null», con índice.
--
-- NO SE HA APLICADO. Se corre en el SQL Editor; después, el archivo se
-- renombra con la versión que registre la base y sube ULTIMA_APLICADA.
-- Prueba: supabase/tests/autorizaciones_y_eliminacion.sql.
-- La app funciona sin esta migración: la casilla del registro se muestra igual,
-- el registro de la constancia falla en silencio y el botón de eliminar dice
-- que todavía no está disponible.
-- ============================================================================

-- ── 1 · Autorizaciones ─────────────────────────────────────────────────────

create table if not exists public.autorizaciones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  documento text not null check (documento in ('terminos_y_privacidad', 'dato_sensible_medico')),
  version text not null check (char_length(version) between 1 and 20),
  aceptada_en timestamptz not null default now(),
  unique (user_id, documento, version)
);
create index if not exists autorizaciones_user_id_idx on public.autorizaciones (user_id);

alter table public.autorizaciones enable row level security;

drop policy if exists "autorizaciones_lee_las_suyas" on public.autorizaciones;
create policy "autorizaciones_lee_las_suyas"
  on public.autorizaciones for select
  to authenticated
  using (user_id = (select auth.uid()));

grant select on table public.autorizaciones to authenticated;

create or replace function public.registrar_autorizacion(p_documento text, p_version text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'no authenticated user' using errcode = '28000';
  end if;
  if p_documento not in ('terminos_y_privacidad', 'dato_sensible_medico') then
    raise exception 'documento_invalido' using errcode = '22023';
  end if;
  if p_version is null or char_length(p_version) not between 1 and 20 then
    raise exception 'version_invalida' using errcode = '22023';
  end if;

  -- Aceptar dos veces la misma versión no duplica: la fecha que vale es la primera.
  insert into public.autorizaciones (user_id, documento, version)
  values (v_user, p_documento, p_version)
  on conflict (user_id, documento, version) do nothing;
end
$$;

revoke all on function public.registrar_autorizacion(text, text) from public, anon;
grant execute on function public.registrar_autorizacion(text, text) to authenticated;

-- ── 2 · El certificado médico, con su autorización ─────────────────────────

create or replace function private.exigir_autorizacion_medica()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.license_type like 'medical_class_%'
     and not exists (
       select 1 from public.autorizaciones a
       where a.user_id = new.user_id and a.documento = 'dato_sensible_medico'
     ) then
    raise exception 'falta_autorizacion_medica'
      using errcode = 'P0001',
            hint = 'El certificado médico es un dato de salud: primero registrar_autorizacion(''dato_sensible_medico'', …).';
  end if;
  return new;
end
$$;

drop trigger if exists exigir_autorizacion_medica on public.licenses_held;
create trigger exigir_autorizacion_medica
  before insert or update of license_type on public.licenses_held
  for each row execute function private.exigir_autorizacion_medica();

-- ── 3 · Eliminar la cuenta ─────────────────────────────────────────────────

-- El piloto puede borrar sus propios archivos de bitácora (su carpeta es su id).
drop policy if exists "bitacoras_borra_lo_suyo" on storage.objects;
create policy "bitacoras_borra_lo_suyo"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'bitacoras'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create or replace function public.eliminar_mi_cuenta(p_confirmacion text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'no authenticated user' using errcode = '28000';
  end if;
  -- La app lo llama primero con otra palabra para saber si la función existe,
  -- antes de borrar los archivos: así no borra archivos de una cuenta que no
  -- se va a poder eliminar.
  if p_confirmacion is distinct from 'ELIMINAR' then
    raise exception 'confirmacion_invalida' using errcode = 'P0001';
  end if;

  -- Lo que no cuelga de auth.users en cascada.
  delete from public.vault_access_log where user_id = v_user;
  update public.verificaciones_horas set revisado_por = null where revisado_por = v_user;
  update public.vault_questions set inserted_by = null where inserted_by = v_user;

  -- El resto (perfil, bitácora, licencias, progreso, intentos, mensajes,
  -- conversaciones, autorizaciones, sesiones) se va en cascada.
  delete from auth.users where id = v_user;

  return jsonb_build_object('eliminado', true);
end
$$;

revoke all on function public.eliminar_mi_cuenta(text) from public, anon;
grant execute on function public.eliminar_mi_cuenta(text) to authenticated;

-- ── 4 · Las dos llaves que impedían borrar a quien revisó o cargó algo ─────

do $llaves$
declare
  v_nombre text;
begin
  select c.conname into v_nombre
  from pg_constraint c
  join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any (c.conkey)
  where c.conrelid = 'public.verificaciones_horas'::regclass and c.contype = 'f' and a.attname = 'revisado_por';
  if v_nombre is not null then
    execute format('alter table public.verificaciones_horas drop constraint %I', v_nombre);
  end if;
  alter table public.verificaciones_horas
    add constraint verificaciones_horas_revisado_por_fkey
    foreign key (revisado_por) references auth.users (id) on delete set null;

  select c.conname into v_nombre
  from pg_constraint c
  join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any (c.conkey)
  where c.conrelid = 'public.vault_questions'::regclass and c.contype = 'f' and a.attname = 'inserted_by';
  if v_nombre is not null then
    execute format('alter table public.vault_questions drop constraint %I', v_nombre);
  end if;
  alter table public.vault_questions
    add constraint vault_questions_inserted_by_fkey
    foreign key (inserted_by) references auth.users (id) on delete set null;
end
$llaves$;

create index if not exists verificaciones_horas_revisado_por_idx on public.verificaciones_horas (revisado_por);
create index if not exists vault_questions_inserted_by_idx on public.vault_questions (inserted_by);
