-- ============================================================================
-- Topes que no se esquivan borrando, topes para lo que no tenía, y límites de
-- tamaño a lo que escribe el cliente.
--
-- Viene de la auditoría de prelanzamiento del 26-sep-2026:
--   · El tope de mensajes y reacciones contaba las filas que EXISTEN en la
--     ventana: el piloto conserva DELETE sobre las suyas, así que publicar y
--     borrar en bucle lo dejaba en cero (y cada mensaje sale por Realtime a
--     todos los del canal).
--   · Postulaciones, vuelos, licencias, respuestas habladas, simulacros ICAO y
--     verificaciones de horas no tenían tope de filas; varios textos y jsonb no
--     tenían tope de tamaño; los archivos de Storage no tenían cupo por piloto.
--   · La reacción aceptaba cualquier texto como emoji, la evidencia de una
--     verificación podía apuntar al archivo de otro piloto, y photo_url
--     aceptaba cualquier URL.
--
-- Qué hace:
--   1. private.registro_de_inserciones: una fila por inserción con tope, que el
--      piloto no puede borrar. El tope cuenta ahí, no en la tabla. Cada
--      inserción poda las filas del mismo piloto y tabla que ya salieron de la
--      ventana, así que el registro no crece sin fin.
--   2. private.insercion_con_tope() cuenta en ese registro. Con un tercer
--      argumento 'sin_fecha' no toca created_at, para las tablas que no lo
--      tienen o lo llaman distinto.
--   3. Topes nuevos (por piloto): postulaciones 30/día, vuelos 100/día,
--      licencias 30/día, respuestas habladas 200/día, simulacros ICAO 20/día,
--      verificaciones de horas 5/día.
--   4. Restricciones de tamaño y forma, NOT VALID: se exigen desde ya a lo
--      nuevo y no fallan por lo que ya hubiera. Comprobado el 26-sep: no hay
--      filas que las violen (0 fotos, 0 reacciones, 0 verificaciones; 2
--      respuestas habladas de 40 caracteres), así que se pueden validar luego
--      con VALIDATE CONSTRAINT.
--   5. Cupo de archivos por piloto: 10 en avatars, 300 en bitacoras.
--
-- NO SE HA APLICADO. Va DESPUÉS de 20261002000000. No borra filas del piloto.
-- Prueba: supabase/tests/topes_y_restricciones.sql.
-- ============================================================================

-- ── 1 · El registro que no se borra ────────────────────────────────────────

create table if not exists private.registro_de_inserciones (
  id bigint generated by default as identity primary key,
  tabla text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  en timestamptz not null default now()
);
create index if not exists registro_de_inserciones_idx
  on private.registro_de_inserciones (user_id, tabla, en desc);
alter table private.registro_de_inserciones enable row level security;
revoke all on table private.registro_de_inserciones from public, anon, authenticated;

-- ── 2 · El tope, contado en el registro ────────────────────────────────────

create or replace function private.insercion_con_tope()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_maximo int := tg_argv[0]::int;
  v_ventana interval := tg_argv[1]::interval;
  v_con_fecha boolean := tg_nargs < 3 or tg_argv[2] <> 'sin_fecha';
  v_recientes int;
begin
  -- La fecha la pone el servidor: nada de mensajes fechados en el futuro.
  if v_con_fecha then
    new.created_at := now();
  end if;

  -- Sin sesión de usuario (service role, tareas del servidor) no hay tope.
  if auth.uid() is null then
    return new;
  end if;

  -- El candado serializa las inserciones del mismo piloto en la misma tabla:
  -- sin él, varias en paralelo leerían el mismo conteo.
  perform pg_advisory_xact_lock(hashtextextended(tg_table_name || ':' || new.user_id::text, 0));

  -- Lo que ya salió de la ventana no cuenta y no hace falta guardarlo.
  delete from private.registro_de_inserciones
  where user_id = new.user_id and tabla = tg_table_name and en <= now() - v_ventana;

  -- Se cuenta en el registro y no en la tabla: borrar lo publicado no devuelve cupo.
  select count(*) into v_recientes
  from private.registro_de_inserciones
  where user_id = new.user_id and tabla = tg_table_name;

  if v_recientes >= v_maximo then
    raise exception 'demasiadas_publicaciones'
      using errcode = 'P0001', hint = format('Máximo %s cada %s.', v_maximo, v_ventana);
  end if;

  insert into private.registro_de_inserciones (tabla, user_id) values (tg_table_name, new.user_id);
  return new;
end
$$;
revoke all on function private.insercion_con_tope() from public;

-- ── 3 · Topes nuevos ───────────────────────────────────────────────────────

drop trigger if exists trg_tope_postulaciones on public.postulaciones;
create trigger trg_tope_postulaciones before insert on public.postulaciones
  for each row execute function private.insercion_con_tope('30', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_flights on public.flights;
create trigger trg_tope_flights before insert on public.flights
  for each row execute function private.insercion_con_tope('100', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_licenses_held on public.licenses_held;
create trigger trg_tope_licenses_held before insert on public.licenses_held
  for each row execute function private.insercion_con_tope('30', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_user_icao_speaking on public.user_icao_speaking;
create trigger trg_tope_user_icao_speaking before insert on public.user_icao_speaking
  for each row execute function private.insercion_con_tope('200', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_user_icao_mock_results on public.user_icao_mock_results;
create trigger trg_tope_user_icao_mock_results before insert on public.user_icao_mock_results
  for each row execute function private.insercion_con_tope('20', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_verificaciones_horas on public.verificaciones_horas;
create trigger trg_tope_verificaciones_horas before insert on public.verificaciones_horas
  for each row execute function private.insercion_con_tope('5', '1 day', 'sin_fecha');

-- ── 4 · Tamaño y forma de lo que escribe el cliente ────────────────────────

alter table public.user_icao_speaking drop constraint if exists user_icao_speaking_tamanos;
alter table public.user_icao_speaking add constraint user_icao_speaking_tamanos check (
  (transcript is null or char_length(transcript) <= 5000)
  and (question_id is null or char_length(question_id) <= 100)
  and (motor is null or char_length(motor) <= 40)
) not valid;

alter table public.user_icao_mock_results drop constraint if exists user_icao_mock_results_scores_tamano;
alter table public.user_icao_mock_results add constraint user_icao_mock_results_scores_tamano
  check (scores is null or pg_column_size(scores) <= 20000) not valid;

alter table public.pilot_state drop constraint if exists pilot_state_licenses_tamano;
alter table public.pilot_state add constraint pilot_state_licenses_tamano
  check (licenses is null or pg_column_size(licenses) <= 20000) not valid;

alter table public.content_reports drop constraint if exists content_reports_contexto_tamano;
alter table public.content_reports add constraint content_reports_contexto_tamano
  check (contexto is null or pg_column_size(contexto) <= 20000) not valid;

-- Una reacción es un emoji, no un texto: hasta 16 caracteres cubre las
-- secuencias con modificadores de tono y las banderas.
alter table public.community_reactions drop constraint if exists community_reactions_emoji_corto;
alter table public.community_reactions add constraint community_reactions_emoji_corto
  check (char_length(emoji) between 1 and 16) not valid;

-- La evidencia de una verificación vive en la carpeta del piloto que la pide.
alter table public.verificaciones_horas drop constraint if exists verificaciones_horas_evidencia_propia;
alter table public.verificaciones_horas add constraint verificaciones_horas_evidencia_propia
  check (evidencia is null or split_part(evidencia, '/', 1) = user_id::text) not valid;

-- La foto de perfil es la del propio piloto en el bucket de avatars, que es la
-- única que la app sube. La CSP ya bloqueaba otras; esto lo dice la base.
alter table public.profiles drop constraint if exists profiles_photo_url_propia;
alter table public.profiles add constraint profiles_photo_url_propia
  check (photo_url is null or photo_url like '%/storage/v1/object/public/avatars/' || id::text || '/%') not valid;

-- ── 5 · Cupo de archivos por piloto ────────────────────────────────────────

drop policy if exists "avatars_authenticated_upload" on storage.objects;
create policy "avatars_authenticated_upload"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (select auth.uid())::text = (storage.foldername(name))[1]
    and (
      select count(*) from storage.objects o
      where o.bucket_id = 'avatars' and (storage.foldername(o.name))[1] = (select auth.uid())::text
    ) < 10
  );

drop policy if exists "bitacoras_sube_lo_suyo" on storage.objects;
create policy "bitacoras_sube_lo_suyo"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'bitacoras'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and (
      select count(*) from storage.objects o
      where o.bucket_id = 'bitacoras' and (storage.foldername(o.name))[1] = (select auth.uid())::text
    ) < 300
  );
