-- ============================================================================
-- Verificar las horas que el piloto dice tener.
--
-- La hoja de vida ya separa lo que Aviatory midió de lo que el piloto declaró,
-- y esa distinción es el argumento para que algún día una aerolínea mire aquí
-- en vez de un PDF. Pero las horas de carrera previa no tenían forma de dejar
-- de ser «declaradas»: no había manera de probarlas.
--
-- Ahora el piloto sube la evidencia (una foto de la página de totales de su
-- bitácora física, un PDF de la escuela, lo que tenga) y alguien de Aviatory la
-- revisa. Quién revisa y con qué criterio se define aparte: aquí queda la
-- estructura para que cuando eso se decida no haya que tocar la base.
--
-- Lo que el piloto NO puede hacer: darse por verificado. Puede pedir revisión y
-- puede retirar una solicitud suya que siga pendiente. El estado lo mueve solo
-- una función de servicio.
--
-- No borra filas.
-- ============================================================================

do $bloque$
begin
  create type public.estado_verificacion as enum ('pendiente', 'verificada', 'rechazada', 'retirada');
exception when duplicate_object then null;
end $bloque$;

create table if not exists public.verificaciones_horas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  estado public.estado_verificacion not null default 'pendiente',
  -- Las horas tal como las declaraba el piloto AL PEDIR la revisión. Si después
  -- las cambia, el sello deja de valer para las nuevas: por eso se guardan aquí
  -- y no se leen de pilot_state al mostrarlas.
  horas_total numeric(7,1) not null check (horas_total between 0 and 50000),
  horas_pic numeric(7,1) not null check (horas_pic >= 0),
  -- Ruta dentro del bucket `bitacoras`. Una foto, un PDF, lo que tenga.
  evidencia text not null check (char_length(evidencia) between 1 and 400),
  nota_piloto text check (char_length(nota_piloto) <= 500),
  nota_revision text check (char_length(nota_revision) <= 500),
  creado_en timestamptz not null default now(),
  revisado_en timestamptz,
  revisado_por uuid references auth.users (id),
  constraint verificaciones_pic_no_supera_total check (horas_pic <= horas_total)
);

comment on table public.verificaciones_horas is
  'Solicitudes de verificación de las horas de carrera previa. El piloto crea y retira; el estado lo mueve revisar_verificacion_horas.';

alter table public.verificaciones_horas enable row level security;
revoke all on table public.verificaciones_horas from anon, authenticated;

create index if not exists verificaciones_horas_user_idx
  on public.verificaciones_horas (user_id, creado_en desc);
create index if not exists verificaciones_horas_pendientes_idx
  on public.verificaciones_horas (creado_en) where estado = 'pendiente';
create index if not exists verificaciones_horas_revisor_idx
  on public.verificaciones_horas (revisado_por);

-- Una sola solicitud pendiente por piloto: si no, se puede llenar la cola.
create unique index if not exists verificaciones_horas_una_pendiente
  on public.verificaciones_horas (user_id) where estado = 'pendiente';

-- El piloto ve las suyas y ninguna más.
create policy "verificaciones_select_own"
  on public.verificaciones_horas for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Y las crea solo para sí mismo, siempre como pendiente.
create policy "verificaciones_insert_own"
  on public.verificaciones_horas for insert
  to authenticated
  with check ((select auth.uid()) = user_id and estado = 'pendiente');

grant select on table public.verificaciones_horas to authenticated;
grant insert (user_id, horas_total, horas_pic, evidencia, nota_piloto) on table public.verificaciones_horas to authenticated;

-- ─── Retirar una solicitud propia ───────────────────────────────────────────

-- Va por función y no por una política de update: con `update` el piloto podría
-- escribir `estado = 'verificada'` sobre su propia fila, que es exactamente lo
-- que no puede pasar en un dato que mira una aerolínea.
create or replace function public.retirar_verificacion_horas()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;

  update public.verificaciones_horas
  set estado = 'retirada'
  where user_id = v_user and estado = 'pendiente';

  return found;
end;
$$;

revoke all on function public.retirar_verificacion_horas() from public, anon;
grant execute on function public.retirar_verificacion_horas() to authenticated;

-- ─── Resolver una revisión ──────────────────────────────────────────────────

-- Todavía no la llama nadie: quién puede revisar se decide aparte. Por eso no
-- tiene permiso de ejecución para el cliente y hoy solo se puede llamar con la
-- llave de servicio. Cuando exista el rol de revisor, se le concede aquí.
create or replace function public.revisar_verificacion_horas(
  p_id bigint,
  p_aprobada boolean,
  p_nota text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.verificaciones_horas
  set estado = case when p_aprobada then 'verificada'::public.estado_verificacion
                    else 'rechazada'::public.estado_verificacion end,
      nota_revision = left(p_nota, 500),
      revisado_en = now(),
      revisado_por = auth.uid()
  where id = p_id and estado = 'pendiente';

  if not found then
    raise exception 'solicitud_no_pendiente' using errcode = '22023';
  end if;
end;
$$;

revoke all on function public.revisar_verificacion_horas(bigint, boolean, text) from public, anon, authenticated;

-- ─── Lo que la hoja de vida necesita saber ──────────────────────────────────

-- Verificada de verdad solo si el sello cubre las horas que el piloto declara
-- HOY: si las sube después de que se las verificaron, el sello deja de aplicar.
create or replace view public.horas_verificadas
with (security_invoker = true) as
select
  v.user_id,
  v.estado,
  v.horas_total,
  v.horas_pic,
  v.revisado_en,
  (v.estado = 'verificada'
    and coalesce(ps.horas_previas_total, 0) <= v.horas_total
    and coalesce(ps.horas_previas_pic, 0) <= v.horas_pic) as cubre_lo_declarado
from public.verificaciones_horas v
join public.pilot_state ps on ps.user_id = v.user_id
where v.id = (
  select v2.id from public.verificaciones_horas v2
  where v2.user_id = v.user_id and v2.estado <> 'retirada'
  order by v2.creado_en desc limit 1
);

comment on view public.horas_verificadas is
  'La última solicitud no retirada de cada piloto, y si su sello cubre las horas que declara hoy.';
grant select on table public.horas_verificadas to authenticated;

-- ─── El archivo de evidencia ────────────────────────────────────────────────

-- Bucket privado: una bitácora lleva matrículas, rutas y fechas del piloto, y
-- no tiene por qué ser pública como los avatares.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'bitacoras', 'bitacoras', false, 10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/pdf']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Cada piloto solo entra a su propia carpeta, que es su id.
drop policy if exists "bitacoras_sube_lo_suyo" on storage.objects;
create policy "bitacoras_sube_lo_suyo"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'bitacoras'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "bitacoras_lee_lo_suyo" on storage.objects;
create policy "bitacoras_lee_lo_suyo"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'bitacoras'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
