-- ============================================================================
-- EL FORO DE LA COMUNIDAD
-- ============================================================================
--
-- La comunidad eran catorce salas de chat que casi nadie usaba (la auditoría
-- del 3 de agosto contó cero mensajes). Nico pidió otra cosa el 26 de
-- septiembre de 2026: un foro al estilo de Reddit enfocado en entrar a una
-- aerolínea, con experiencias de procesos y entrevistas, avisos rápidos «como
-- en Waze», votos y comentarios. Y que se pueda leer sin cuenta para que
-- Google lo encuentre, pero que para ver más haya que entrar.
--
-- Cómo queda:
--   1. foro_categorias: seis, fijas, las escribe esta migración.
--   2. foro_publicaciones, foro_comentarios, sus votos, las confirmaciones de
--      los avisos y los reportes. RLS encendido, sin políticas y sin permisos:
--      el cliente no toca las tablas, todo va por funciones.
--   3. Leer, con o sin sesión: foro_feed, foro_publicacion, foro_tendencias y
--      foro_mapa. Son la primera lectura abierta a anon que tiene la base, y
--      por eso devuelven solo lo publicado y nunca un id de usuario: el autor
--      sale por su nombre de usuario, o como anónimo. Sin sesión se ve la
--      primera página del feed y los tres comentarios con más puntos de cada
--      publicación; lo demás pide entrar.
--   4. Escribir, con sesión: publicar, editar, borrar, votar, confirmar un
--      aviso, comentar, votar un comentario, borrar un comentario y reportar.
--      Borrar cambia el estado; la fila se queda.
--   5. Topes por piloto, contados en el registro que no se borra
--      (private.insercion_con_tope): 10 publicaciones, 120 comentarios, 500
--      votos, 100 confirmaciones y 20 reportes al día.
--   6. Moderación: con tres reportes de pilotos distintos, la publicación o el
--      comentario se ocultan hasta que alguien los revise desde el panel de
--      Supabase (tabla foro_reportes).
--   7. Publicar o comentar por primera vez gana «Hola comunidad», y comentar
--      avisa al autor (tipo foro_respuesta, de la migración anterior).
--
-- Va DESPUÉS de 20261002010000 (el tope nuevo) y de 20261003000000 (el tipo
-- de aviso). NO SE HA APLICADO. No toca filas que ya existan.
-- Prueba: supabase/tests/foro.sql.
-- ============================================================================

do $$
begin
  if to_regclass('private.registro_de_inserciones') is null then
    raise exception 'Falta 20261002010000_topes_y_restricciones: el foro cuenta sus topes en private.registro_de_inserciones.';
  end if;
  if not exists (
    select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid
    where t.typname = 'notification_type' and e.enumlabel = 'foro_respuesta'
  ) then
    raise exception 'Falta 20261003000000_aviso_del_foro: el tipo de aviso foro_respuesta.';
  end if;
end
$$;

-- ── 1 · Categorías ─────────────────────────────────────────────────────────

create table if not exists public.foro_categorias (
  clave text primary key check (clave ~ '^[a-z][a-z-]{1,30}$'),
  nombre text not null,
  descripcion text not null,
  orden integer not null default 0
);
alter table public.foro_categorias enable row level security;

-- El cliente tiene la misma lista en src/lib/foro.ts, con sus íconos; una
-- prueba compara las claves con estas.
insert into public.foro_categorias (clave, nombre, descripcion, orden) values
  ('convocatorias', 'Convocatorias', 'Quién está contratando, con qué requisitos y hasta cuándo. Comparte el enlace oficial.', 1),
  ('entrevistas', 'Entrevistas y procesos', 'Cómo te fue: etapas, preguntas, simulador y psicotécnicas.', 2),
  ('avisos', 'Avisos rápidos', 'Lo que está pasando ahora, como en Waze. Los demás confirman si sigue vigente.', 3),
  ('cursos', 'Cursos y habilitaciones', 'Type rating, inglés ICAO, simulador y escuelas: qué sirvió y cuánto costó.', 4),
  ('preguntas', 'Preguntas', 'Pregunta lo que necesites a pilotos que ya pasaron por ahí.', 5),
  ('vida-en-linea', 'Vida en aerolínea', 'Bases, horarios, rutas y el primer año de línea, contados desde adentro.', 6)
on conflict (clave) do update
  set nombre = excluded.nombre, descripcion = excluded.descripcion, orden = excluded.orden;

-- ── 2 · Publicaciones, comentarios, votos, confirmaciones y reportes ───────

create table if not exists public.foro_publicaciones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  categoria text not null references public.foro_categorias (clave),
  titulo text not null check (char_length(titulo) between 8 and 140),
  cuerpo text not null default '' check (char_length(cuerpo) <= 10000),
  aerolinea_id bigint references public.airlines (id),
  ciudad text check (ciudad is null or char_length(ciudad) between 2 and 60),
  anonima boolean not null default false,
  estado text not null default 'publicada' check (estado in ('publicada', 'oculta', 'eliminada')),
  puntos integer not null default 0,
  comentarios integer not null default 0,
  confirmaciones integer not null default 0,
  desmentidos integer not null default 0,
  reportes integer not null default 0,
  creada_en timestamptz not null default now(),
  editada_en timestamptz,
  actividad_en timestamptz not null default now(),
  -- Solo los avisos: hasta cuándo se dan por vigentes. Confirmar lo alarga.
  vigente_hasta timestamptz,
  constraint foro_aviso_con_aerolinea check (categoria <> 'avisos' or aerolinea_id is not null)
);
create index if not exists foro_publicaciones_estado_idx on public.foro_publicaciones (estado, creada_en desc);
create index if not exists foro_publicaciones_categoria_idx on public.foro_publicaciones (categoria, estado, creada_en desc);
create index if not exists foro_publicaciones_user_idx on public.foro_publicaciones (user_id);
create index if not exists foro_publicaciones_aerolinea_idx on public.foro_publicaciones (aerolinea_id);
alter table public.foro_publicaciones enable row level security;

create table if not exists public.foro_comentarios (
  id bigint generated by default as identity primary key,
  publicacion_id bigint not null references public.foro_publicaciones (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Dos niveles: una respuesta a una respuesta cuelga del comentario raíz. Si
  -- el raíz desaparece (se elimina la cuenta), la respuesta sube de nivel.
  padre_id bigint references public.foro_comentarios (id) on delete set null,
  cuerpo text not null check (char_length(cuerpo) between 1 and 5000),
  anonimo boolean not null default false,
  estado text not null default 'publicado' check (estado in ('publicado', 'oculto', 'eliminado')),
  puntos integer not null default 0,
  reportes integer not null default 0,
  creado_en timestamptz not null default now()
);
create index if not exists foro_comentarios_publicacion_idx on public.foro_comentarios (publicacion_id, creado_en);
create index if not exists foro_comentarios_user_idx on public.foro_comentarios (user_id);
create index if not exists foro_comentarios_padre_idx on public.foro_comentarios (padre_id);
alter table public.foro_comentarios enable row level security;

create table if not exists public.foro_votos (
  publicacion_id bigint not null references public.foro_publicaciones (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  valor smallint not null check (valor in (-1, 1)),
  creado_en timestamptz not null default now(),
  primary key (publicacion_id, user_id)
);
create index if not exists foro_votos_user_idx on public.foro_votos (user_id);
alter table public.foro_votos enable row level security;

create table if not exists public.foro_votos_comentario (
  comentario_id bigint not null references public.foro_comentarios (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  valor smallint not null check (valor in (-1, 1)),
  creado_en timestamptz not null default now(),
  primary key (comentario_id, user_id)
);
create index if not exists foro_votos_comentario_user_idx on public.foro_votos_comentario (user_id);
alter table public.foro_votos_comentario enable row level security;

-- «¿Sigue vigente?» de los avisos: sí o ya no, uno por piloto.
create table if not exists public.foro_confirmaciones (
  publicacion_id bigint not null references public.foro_publicaciones (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  sigue boolean not null,
  creada_en timestamptz not null default now(),
  primary key (publicacion_id, user_id)
);
create index if not exists foro_confirmaciones_user_idx on public.foro_confirmaciones (user_id);
alter table public.foro_confirmaciones enable row level security;

create table if not exists public.foro_reportes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  publicacion_id bigint references public.foro_publicaciones (id) on delete cascade,
  comentario_id bigint references public.foro_comentarios (id) on delete cascade,
  motivo text not null check (motivo in ('spam', 'ofensivo', 'falso', 'datos_personales', 'otro')),
  detalle text check (detalle is null or char_length(detalle) <= 500),
  revisado boolean not null default false,
  creado_en timestamptz not null default now(),
  constraint foro_reporte_de_una_cosa check (num_nonnulls(publicacion_id, comentario_id) = 1)
);
create unique index if not exists foro_reportes_una_vez_publicacion on public.foro_reportes (user_id, publicacion_id) where publicacion_id is not null;
create unique index if not exists foro_reportes_una_vez_comentario on public.foro_reportes (user_id, comentario_id) where comentario_id is not null;
create index if not exists foro_reportes_publicacion_idx on public.foro_reportes (publicacion_id);
create index if not exists foro_reportes_comentario_idx on public.foro_reportes (comentario_id);
alter table public.foro_reportes enable row level security;

revoke all on table
  public.foro_categorias, public.foro_publicaciones, public.foro_comentarios, public.foro_votos,
  public.foro_votos_comentario, public.foro_confirmaciones, public.foro_reportes
from public, anon, authenticated;

-- ── 3 · Topes ──────────────────────────────────────────────────────────────

drop trigger if exists trg_tope_foro_publicaciones on public.foro_publicaciones;
create trigger trg_tope_foro_publicaciones before insert on public.foro_publicaciones
  for each row execute function private.insercion_con_tope('10', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_foro_comentarios on public.foro_comentarios;
create trigger trg_tope_foro_comentarios before insert on public.foro_comentarios
  for each row execute function private.insercion_con_tope('120', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_foro_votos on public.foro_votos;
create trigger trg_tope_foro_votos before insert on public.foro_votos
  for each row execute function private.insercion_con_tope('500', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_foro_votos_comentario on public.foro_votos_comentario;
create trigger trg_tope_foro_votos_comentario before insert on public.foro_votos_comentario
  for each row execute function private.insercion_con_tope('500', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_foro_confirmaciones on public.foro_confirmaciones;
create trigger trg_tope_foro_confirmaciones before insert on public.foro_confirmaciones
  for each row execute function private.insercion_con_tope('100', '1 day', 'sin_fecha');

drop trigger if exists trg_tope_foro_reportes on public.foro_reportes;
create trigger trg_tope_foro_reportes before insert on public.foro_reportes
  for each row execute function private.insercion_con_tope('20', '1 day', 'sin_fecha');

-- ── 4 · Cómo sale cada cosa (privadas) ─────────────────────────────────────

-- El autor tal como se muestra: usuario, foto y racha. Nunca el id.
create or replace function private.foro_autor(p_user uuid, p_anonimo boolean)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select case when p_anonimo then null else (
    select jsonb_build_object('usuario', p.username, 'foto', p.photo_url, 'racha', coalesce(s.current_streak, 0))
    from public.profiles p
    left join public.streaks s on s.user_id = p.id
    where p.id = p_user
  ) end
$$;

-- Lo que sube una publicación en «Tendencia»: puntos, comentarios y
-- confirmaciones, divididos por la edad. La fórmula de Hacker News, con los
-- comentarios pesando doble porque en un foro de ayuda la conversación es lo
-- que vale.
create or replace function private.foro_calor(p_puntos integer, p_comentarios integer, p_confirmaciones integer, p_creada timestamptz)
returns double precision
language sql
stable
set search_path = ''
as $$
  select (greatest(p_puntos, 0) + 2 * p_comentarios + p_confirmaciones + 1)::double precision
    / power(extract(epoch from (now() - p_creada)) / 3600.0 + 2, 1.5)
$$;

create or replace function private.foro_tarjeta(p public.foro_publicaciones, p_yo uuid, p_completa boolean)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', p.id,
    'categoria', p.categoria,
    'titulo', p.titulo,
    'cuerpo', case when p_completa then p.cuerpo else left(p.cuerpo, 280) end,
    'recortado', not p_completa and char_length(p.cuerpo) > 280,
    'aerolinea', (
      select jsonb_build_object('id', a.id, 'nombre', a.name, 'codigo', a.code, 'color', a.brand_color)
      from public.airlines a where a.id = p.aerolinea_id
    ),
    'ciudad', p.ciudad,
    'autor', private.foro_autor(p.user_id, p.anonima),
    'anonima', p.anonima,
    'puntos', p.puntos,
    'comentarios', p.comentarios,
    'confirmaciones', p.confirmaciones,
    'desmentidos', p.desmentidos,
    'vigente', case when p.categoria = 'avisos' then
      coalesce(p.vigente_hasta > now(), false) and not (p.desmentidos >= 3 and p.desmentidos > p.confirmaciones)
    end,
    'estado', p.estado,
    'creada_en', p.creada_en,
    'editada_en', p.editada_en,
    'mi_voto', case when p_yo is null then 0 else coalesce((
      select v.valor from public.foro_votos v where v.publicacion_id = p.id and v.user_id = p_yo
    ), 0) end,
    'mi_confirmacion', case when p_yo is null then null else (
      select c.sigue from public.foro_confirmaciones c where c.publicacion_id = p.id and c.user_id = p_yo
    ) end,
    'es_mia', p_yo is not null and p.user_id = p_yo
  )
$$;

-- p_autor_publicacion va nulo si la publicación es anónima: marcar «autor» en
-- un comentario con nombre delataría quién escribió la publicación.
create or replace function private.foro_comentario(c public.foro_comentarios, p_yo uuid, p_autor_publicacion uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', c.id,
    'padre_id', c.padre_id,
    'cuerpo', case when c.estado = 'publicado' then c.cuerpo else '' end,
    'estado', c.estado,
    'autor', case when c.estado = 'publicado' then private.foro_autor(c.user_id, c.anonimo) end,
    'es_del_autor', c.estado = 'publicado' and not c.anonimo and p_autor_publicacion is not null
      and c.user_id = p_autor_publicacion,
    'puntos', c.puntos,
    'creado_en', c.creado_en,
    'mi_voto', case when p_yo is null then 0 else coalesce((
      select v.valor from public.foro_votos_comentario v where v.comentario_id = c.id and v.user_id = p_yo
    ), 0) end,
    'es_mio', p_yo is not null and c.user_id = p_yo
  )
$$;

-- Un aviso por publicación mientras no lo lea: diez comentarios seguidos no
-- son diez campanas.
create or replace function private.foro_avisar(p_destino uuid, p_autor uuid, p_titulo text, p_cuerpo text, p_publicacion bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_url text := '/app/comunidad/p/' || p_publicacion;
begin
  if p_destino is null or p_destino = p_autor then
    return;
  end if;
  if exists (
    select 1 from public.notifications n
    where n.user_id = p_destino and n.type = 'foro_respuesta' and n.action_url = v_url and n.read_at is null
  ) then
    return;
  end if;
  insert into public.notifications (user_id, type, title, body, icon, action_url)
  values (p_destino, 'foro_respuesta', p_titulo, left(p_cuerpo, 140), '💬', v_url);
end
$$;

-- «Hola comunidad» también se gana en el foro. Va directo y no por
-- desbloquear_logros, que es de las funciones compartidas y no se republica
-- por esto.
create or replace function private.foro_primer_paso(p_user uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.user_achievements (user_id, achievement_id)
  select p_user, a.id from public.achievements a where a.code = 'community_hello'
  on conflict do nothing
$$;

revoke all on function private.foro_autor(uuid, boolean) from public;
revoke all on function private.foro_calor(integer, integer, integer, timestamptz) from public;
revoke all on function private.foro_tarjeta(public.foro_publicaciones, uuid, boolean) from public;
revoke all on function private.foro_comentario(public.foro_comentarios, uuid, uuid) from public;
revoke all on function private.foro_avisar(uuid, uuid, text, text, bigint) from public;
revoke all on function private.foro_primer_paso(uuid) from public;

-- ── 5 · Leer: con o sin sesión ─────────────────────────────────────────────

create or replace function public.foro_feed(
  p_categoria text default null,
  p_orden text default 'tendencia',
  p_aerolinea bigint default null,
  p_pagina integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_por_pagina constant integer := 20;
  v_filas jsonb;
  v_hay_mas boolean;
begin
  if p_orden is null or p_orden not in ('tendencia', 'nuevo', 'top') then
    raise exception 'orden_invalido' using errcode = '22023';
  end if;
  if p_pagina is null or p_pagina < 0 or p_pagina > 50 then
    raise exception 'pagina_invalida' using errcode = '22023';
  end if;

  -- Sin sesión se ve la primera página: para seguir hay que entrar.
  if v_yo is null and p_pagina > 0 then
    return jsonb_build_object('publicaciones', '[]'::jsonb, 'hay_mas', false, 'requiere_sesion', true);
  end if;

  with pagina as (
    select
      p.id,
      p.creada_en,
      case p_orden
        when 'tendencia' then private.foro_calor(p.puntos, p.comentarios, p.confirmaciones, p.creada_en)
        when 'top' then p.puntos::double precision
      end as clave
    from public.foro_publicaciones p
    where p.estado = 'publicada'
      and (p_categoria is null or p.categoria = p_categoria)
      and (p_aerolinea is null or p.aerolinea_id = p_aerolinea)
      and (p_orden = 'nuevo' or p.creada_en > now() - interval '90 days')
      and (p_orden <> 'top' or p.creada_en > now() - interval '30 days')
    order by clave desc nulls last, p.creada_en desc, p.id desc
    limit v_por_pagina + 1
    offset p_pagina * v_por_pagina
  ),
  numerada as (
    select id, row_number() over (order by clave desc nulls last, creada_en desc, id desc) as n
    from pagina
  )
  select
    coalesce(jsonb_agg(private.foro_tarjeta(p, v_yo, false) order by nu.n) filter (where nu.n <= v_por_pagina), '[]'::jsonb),
    count(*) > v_por_pagina
  into v_filas, v_hay_mas
  from numerada nu
  join public.foro_publicaciones p on p.id = nu.id;

  return jsonb_build_object(
    'publicaciones', v_filas,
    'hay_mas', v_hay_mas and v_yo is not null,
    'requiere_sesion', v_yo is null and v_hay_mas
  );
end
$$;

create or replace function public.foro_publicacion(p_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_p public.foro_publicaciones;
  v_autor uuid;
  v_comentarios jsonb;
  v_total integer;
begin
  select * into v_p from public.foro_publicaciones where id = p_id;
  -- La oculta la sigue viendo su autor, con el aviso de que está en revisión.
  if not found or v_p.estado = 'eliminada' or (v_p.estado = 'oculta' and v_p.user_id is distinct from v_yo) then
    return null;
  end if;
  v_autor := case when v_p.anonima then null else v_p.user_id end;

  select count(*) into v_total
  from public.foro_comentarios c
  where c.publicacion_id = p_id and c.estado = 'publicado';

  if v_yo is null then
    -- Sin sesión: los tres comentarios con más puntos, sin sus respuestas.
    select coalesce(jsonb_agg(private.foro_comentario(s.c, null, v_autor) order by (s.c).puntos desc, (s.c).creado_en), '[]'::jsonb)
    into v_comentarios
    from (
      select c
      from public.foro_comentarios c
      where c.publicacion_id = p_id and c.estado = 'publicado' and c.padre_id is null
      order by c.puntos desc, c.creado_en
      limit 3
    ) s;
  else
    -- Con sesión, todos. Un comentario eliminado se queda como hueco si tiene
    -- respuestas, para que la conversación no quede colgando.
    select coalesce(jsonb_agg(private.foro_comentario(s.c, v_yo, v_autor) order by (s.c).creado_en), '[]'::jsonb)
    into v_comentarios
    from (
      select c
      from public.foro_comentarios c
      where c.publicacion_id = p_id
        and (
          c.estado = 'publicado'
          or exists (
            select 1 from public.foro_comentarios r
            where r.padre_id = c.id and r.estado = 'publicado'
          )
        )
      order by c.creado_en
      limit 500
    ) s;
  end if;

  return jsonb_build_object(
    'publicacion', private.foro_tarjeta(v_p, v_yo, true),
    'comentarios', v_comentarios,
    'total_comentarios', v_total,
    'requiere_sesion', v_yo is null
  );
end
$$;

create or replace function public.foro_tendencias()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'categorias', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'clave', c.clave,
        'nombre', c.nombre,
        'descripcion', c.descripcion,
        'semana', (
          select count(*) from public.foro_publicaciones p
          where p.categoria = c.clave and p.estado = 'publicada' and p.creada_en > now() - interval '7 days'
        )
      ) order by c.orden), '[]'::jsonb)
      from public.foro_categorias c
    ),
    'aerolineas', (
      select coalesce(jsonb_agg(t.fila order by t.n desc, t.fila ->> 'nombre'), '[]'::jsonb)
      from (
        select
          jsonb_build_object('id', a.id, 'nombre', a.name, 'codigo', a.code, 'color', a.brand_color, 'publicaciones', count(*)) as fila,
          count(*) as n
        from public.foro_publicaciones p
        join public.airlines a on a.id = p.aerolinea_id
        where p.estado = 'publicada' and p.creada_en > now() - interval '30 days'
        group by a.id
        order by count(*) desc, a.name
        limit 8
      ) t
    ),
    'avisos', (
      select coalesce(jsonb_agg(private.foro_tarjeta(v.p, auth.uid(), false) order by (v.p).creada_en desc), '[]'::jsonb)
      from (
        select p
        from public.foro_publicaciones p
        where p.categoria = 'avisos' and p.estado = 'publicada' and p.vigente_hasta > now()
          and not (p.desmentidos >= 3 and p.desmentidos > p.confirmaciones)
        order by p.creada_en desc
        limit 5
      ) v
    )
  )
$$;

-- Para el sitemap: lo publicado y cuándo cambió por última vez.
create or replace function public.foro_mapa()
returns table (id bigint, titulo text, actualizada timestamptz)
language sql
stable
security definer
set search_path = ''
as $$
  select p.id, p.titulo, greatest(p.creada_en, coalesce(p.editada_en, p.creada_en), p.actividad_en)
  from public.foro_publicaciones p
  where p.estado = 'publicada'
  order by p.creada_en desc
  limit 5000
$$;

-- ── 6 · Escribir: con sesión ───────────────────────────────────────────────

create or replace function public.foro_publicar(
  p_categoria text,
  p_titulo text,
  p_cuerpo text default '',
  p_aerolinea bigint default null,
  p_ciudad text default null,
  p_anonima boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_titulo text := btrim(coalesce(p_titulo, ''));
  v_cuerpo text := btrim(coalesce(p_cuerpo, ''));
  v_ciudad text := nullif(btrim(coalesce(p_ciudad, '')), '');
  v_id bigint;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if not exists (select 1 from public.foro_categorias where clave = p_categoria) then
    raise exception 'categoria_invalida' using errcode = '22023';
  end if;
  if char_length(v_titulo) < 8 or char_length(v_titulo) > 140 then
    raise exception 'titulo_invalido' using errcode = '22023';
  end if;
  if char_length(v_cuerpo) > 10000 then
    raise exception 'cuerpo_invalido' using errcode = '22023';
  end if;
  if p_categoria = 'avisos' and p_aerolinea is null then
    raise exception 'aviso_sin_aerolinea' using errcode = '22023';
  end if;
  if p_aerolinea is not null and not exists (select 1 from public.airlines where id = p_aerolinea) then
    raise exception 'aerolinea_invalida' using errcode = '22023';
  end if;
  if v_ciudad is not null and char_length(v_ciudad) not between 2 and 60 then
    raise exception 'ciudad_invalida' using errcode = '22023';
  end if;

  insert into public.foro_publicaciones (user_id, categoria, titulo, cuerpo, aerolinea_id, ciudad, anonima, puntos, vigente_hasta)
  values (
    v_yo, p_categoria, v_titulo, v_cuerpo, p_aerolinea, v_ciudad, coalesce(p_anonima, false), 1,
    case when p_categoria = 'avisos' then now() + interval '30 days' end
  )
  returning id into v_id;

  -- Como en Reddit, la publicación nace con el voto de quien la escribe.
  insert into public.foro_votos (publicacion_id, user_id, valor) values (v_id, v_yo, 1);
  perform private.foro_primer_paso(v_yo);
  return v_id;
end
$$;

-- El título no se edita (los votos y los comentarios fueron sobre ese título);
-- el cuerpo sí, y queda marcado.
create or replace function public.foro_editar(p_id bigint, p_cuerpo text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_cuerpo text := btrim(coalesce(p_cuerpo, ''));
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if char_length(v_cuerpo) > 10000 then
    raise exception 'cuerpo_invalido' using errcode = '22023';
  end if;
  update public.foro_publicaciones
  set cuerpo = v_cuerpo, editada_en = now()
  where id = p_id and user_id = v_yo and estado <> 'eliminada';
  if not found then
    raise exception 'no_encontrada' using errcode = 'P0002';
  end if;
end
$$;

create or replace function public.foro_borrar(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  update public.foro_publicaciones set estado = 'eliminada'
  where id = p_id and user_id = v_yo and estado <> 'eliminada';
  if not found then
    raise exception 'no_encontrada' using errcode = 'P0002';
  end if;
end
$$;

create or replace function public.foro_votar(p_publicacion bigint, p_valor integer)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_antes integer;
  v_puntos integer;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if p_valor is null or p_valor not in (-1, 0, 1) then
    raise exception 'voto_invalido' using errcode = '22023';
  end if;
  -- El candado sobre la publicación ordena los votos que llegan a la vez:
  -- el contador se mueve por diferencia y no se pierde ninguno.
  perform 1 from public.foro_publicaciones where id = p_publicacion and estado = 'publicada' for update;
  if not found then
    raise exception 'no_encontrada' using errcode = 'P0002';
  end if;

  select valor into v_antes from public.foro_votos where publicacion_id = p_publicacion and user_id = v_yo;
  v_antes := coalesce(v_antes, 0);
  if p_valor = 0 and v_antes <> 0 then
    delete from public.foro_votos where publicacion_id = p_publicacion and user_id = v_yo;
  elsif p_valor <> 0 and v_antes = 0 then
    insert into public.foro_votos (publicacion_id, user_id, valor) values (p_publicacion, v_yo, p_valor);
  elsif p_valor <> 0 and p_valor <> v_antes then
    update public.foro_votos set valor = p_valor, creado_en = now()
    where publicacion_id = p_publicacion and user_id = v_yo;
  end if;

  update public.foro_publicaciones set puntos = puntos + (p_valor - v_antes)
  where id = p_publicacion
  returning puntos into v_puntos;
  return jsonb_build_object('puntos', v_puntos, 'mi_voto', p_valor);
end
$$;

-- «¿Sigue vigente?»: sí, ya no, o nulo para retirar lo que dijo.
create or replace function public.foro_confirmar(p_publicacion bigint, p_sigue boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_p public.foro_publicaciones;
  v_antes boolean;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  select * into v_p from public.foro_publicaciones where id = p_publicacion and estado = 'publicada' for update;
  if not found then
    raise exception 'no_encontrada' using errcode = 'P0002';
  end if;
  if v_p.categoria <> 'avisos' then
    raise exception 'no_es_aviso' using errcode = '22023';
  end if;
  if v_p.user_id = v_yo then
    raise exception 'aviso_propio' using errcode = '22023';
  end if;

  select sigue into v_antes from public.foro_confirmaciones where publicacion_id = p_publicacion and user_id = v_yo;
  if p_sigue is null then
    delete from public.foro_confirmaciones where publicacion_id = p_publicacion and user_id = v_yo;
  elsif v_antes is null then
    insert into public.foro_confirmaciones (publicacion_id, user_id, sigue) values (p_publicacion, v_yo, p_sigue);
  elsif v_antes <> p_sigue then
    update public.foro_confirmaciones set sigue = p_sigue, creada_en = now()
    where publicacion_id = p_publicacion and user_id = v_yo;
  end if;

  update public.foro_publicaciones
  set
    confirmaciones = confirmaciones + (case when p_sigue then 1 else 0 end) - (case when v_antes then 1 else 0 end),
    desmentidos = desmentidos + (case when p_sigue = false then 1 else 0 end) - (case when v_antes = false then 1 else 0 end),
    vigente_hasta = case when p_sigue then greatest(coalesce(vigente_hasta, now()), now() + interval '30 days') else vigente_hasta end,
    actividad_en = now()
  where id = p_publicacion
  returning * into v_p;

  return jsonb_build_object(
    'confirmaciones', v_p.confirmaciones,
    'desmentidos', v_p.desmentidos,
    'vigente', coalesce(v_p.vigente_hasta > now(), false) and not (v_p.desmentidos >= 3 and v_p.desmentidos > v_p.confirmaciones),
    'mi_confirmacion', p_sigue
  );
end
$$;

create or replace function public.foro_comentar(
  p_publicacion bigint,
  p_cuerpo text,
  p_padre bigint default null,
  p_anonimo boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_cuerpo text := btrim(coalesce(p_cuerpo, ''));
  v_p public.foro_publicaciones;
  v_padre public.foro_comentarios;
  v_c public.foro_comentarios;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if char_length(v_cuerpo) < 1 or char_length(v_cuerpo) > 5000 then
    raise exception 'comentario_invalido' using errcode = '22023';
  end if;
  select * into v_p from public.foro_publicaciones where id = p_publicacion and estado = 'publicada' for update;
  if not found then
    raise exception 'no_encontrada' using errcode = 'P0002';
  end if;

  if p_padre is not null then
    select * into v_padre from public.foro_comentarios
    where id = p_padre and publicacion_id = p_publicacion and estado = 'publicado';
    if not found then
      raise exception 'comentario_no_encontrado' using errcode = 'P0002';
    end if;
    -- Dos niveles: la respuesta a una respuesta cuelga del mismo raíz.
    if v_padre.padre_id is not null then
      select * into v_padre from public.foro_comentarios where id = v_padre.padre_id;
    end if;
  end if;

  insert into public.foro_comentarios (publicacion_id, user_id, padre_id, cuerpo, anonimo)
  values (p_publicacion, v_yo, v_padre.id, v_cuerpo, coalesce(p_anonimo, false))
  returning * into v_c;

  update public.foro_publicaciones set comentarios = comentarios + 1, actividad_en = now()
  where id = p_publicacion;

  perform private.foro_avisar(v_p.user_id, v_yo, 'Comentaron tu publicación', v_p.titulo, v_p.id);
  if v_padre.id is not null and v_padre.user_id <> v_p.user_id then
    perform private.foro_avisar(v_padre.user_id, v_yo, 'Respondieron tu comentario', v_p.titulo, v_p.id);
  end if;
  perform private.foro_primer_paso(v_yo);

  return private.foro_comentario(v_c, v_yo, case when v_p.anonima then null else v_p.user_id end);
end
$$;

create or replace function public.foro_votar_comentario(p_comentario bigint, p_valor integer)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_antes integer;
  v_puntos integer;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if p_valor is null or p_valor not in (-1, 0, 1) then
    raise exception 'voto_invalido' using errcode = '22023';
  end if;
  perform 1 from public.foro_comentarios c
  join public.foro_publicaciones p on p.id = c.publicacion_id
  where c.id = p_comentario and c.estado = 'publicado' and p.estado = 'publicada'
  for update of c;
  if not found then
    raise exception 'comentario_no_encontrado' using errcode = 'P0002';
  end if;

  select valor into v_antes from public.foro_votos_comentario where comentario_id = p_comentario and user_id = v_yo;
  v_antes := coalesce(v_antes, 0);
  if p_valor = 0 and v_antes <> 0 then
    delete from public.foro_votos_comentario where comentario_id = p_comentario and user_id = v_yo;
  elsif p_valor <> 0 and v_antes = 0 then
    insert into public.foro_votos_comentario (comentario_id, user_id, valor) values (p_comentario, v_yo, p_valor);
  elsif p_valor <> 0 and p_valor <> v_antes then
    update public.foro_votos_comentario set valor = p_valor, creado_en = now()
    where comentario_id = p_comentario and user_id = v_yo;
  end if;

  update public.foro_comentarios set puntos = puntos + (p_valor - v_antes)
  where id = p_comentario
  returning puntos into v_puntos;
  return jsonb_build_object('puntos', v_puntos, 'mi_voto', p_valor);
end
$$;

create or replace function public.foro_borrar_comentario(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_publicacion bigint;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  update public.foro_comentarios set estado = 'eliminado'
  where id = p_id and user_id = v_yo and estado = 'publicado'
  returning publicacion_id into v_publicacion;
  if not found then
    raise exception 'comentario_no_encontrado' using errcode = 'P0002';
  end if;
  update public.foro_publicaciones set comentarios = greatest(comentarios - 1, 0) where id = v_publicacion;
end
$$;

-- Con tres reportes de pilotos distintos se oculta hasta que alguien lo
-- revise. Devuelve si el reporte contó (el mismo piloto no cuenta dos veces).
create or replace function public.foro_reportar(
  p_publicacion bigint,
  p_comentario bigint,
  p_motivo text,
  p_detalle text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_yo uuid := auth.uid();
  v_detalle text := nullif(btrim(coalesce(p_detalle, '')), '');
  v_dueno uuid;
  v_publicacion bigint;
  v_contado integer;
  v_estado text;
begin
  if v_yo is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if num_nonnulls(p_publicacion, p_comentario) <> 1 then
    raise exception 'reporte_invalido' using errcode = '22023';
  end if;
  if p_motivo is null or p_motivo not in ('spam', 'ofensivo', 'falso', 'datos_personales', 'otro') then
    raise exception 'motivo_invalido' using errcode = '22023';
  end if;
  if v_detalle is not null and char_length(v_detalle) > 500 then
    raise exception 'detalle_invalido' using errcode = '22023';
  end if;

  if p_publicacion is not null then
    select user_id into v_dueno from public.foro_publicaciones
    where id = p_publicacion and estado = 'publicada' for update;
    if not found then
      raise exception 'no_encontrada' using errcode = 'P0002';
    end if;
    if v_dueno = v_yo then
      raise exception 'reporte_propio' using errcode = '22023';
    end if;
    insert into public.foro_reportes (user_id, publicacion_id, motivo, detalle)
    values (v_yo, p_publicacion, p_motivo, v_detalle)
    on conflict do nothing;
    get diagnostics v_contado = row_count;
    if v_contado = 1 then
      update public.foro_publicaciones
      set reportes = reportes + 1, estado = case when reportes + 1 >= 3 then 'oculta' else estado end
      where id = p_publicacion;
    end if;
  else
    select c.user_id, c.publicacion_id into v_dueno, v_publicacion from public.foro_comentarios c
    where c.id = p_comentario and c.estado = 'publicado' for update;
    if not found then
      raise exception 'comentario_no_encontrado' using errcode = 'P0002';
    end if;
    if v_dueno = v_yo then
      raise exception 'reporte_propio' using errcode = '22023';
    end if;
    insert into public.foro_reportes (user_id, comentario_id, motivo, detalle)
    values (v_yo, p_comentario, p_motivo, v_detalle)
    on conflict do nothing;
    get diagnostics v_contado = row_count;
    if v_contado = 1 then
      update public.foro_comentarios
      set reportes = reportes + 1, estado = case when reportes + 1 >= 3 then 'oculto' else estado end
      where id = p_comentario
      returning estado into v_estado;
      -- Estaba publicado (se leyó así arriba): si ahora está oculto, deja de
      -- contar en la publicación.
      if v_estado = 'oculto' then
        update public.foro_publicaciones set comentarios = greatest(comentarios - 1, 0) where id = v_publicacion;
      end if;
    end if;
  end if;
  return v_contado = 1;
end
$$;

-- ── 7 · Permisos ───────────────────────────────────────────────────────────

revoke all on function public.foro_feed(text, text, bigint, integer) from public, anon, authenticated;
revoke all on function public.foro_publicacion(bigint) from public, anon, authenticated;
revoke all on function public.foro_tendencias() from public, anon, authenticated;
revoke all on function public.foro_mapa() from public, anon, authenticated;
revoke all on function public.foro_publicar(text, text, text, bigint, text, boolean) from public, anon, authenticated;
revoke all on function public.foro_editar(bigint, text) from public, anon, authenticated;
revoke all on function public.foro_borrar(bigint) from public, anon, authenticated;
revoke all on function public.foro_votar(bigint, integer) from public, anon, authenticated;
revoke all on function public.foro_confirmar(bigint, boolean) from public, anon, authenticated;
revoke all on function public.foro_comentar(bigint, text, bigint, boolean) from public, anon, authenticated;
revoke all on function public.foro_votar_comentario(bigint, integer) from public, anon, authenticated;
revoke all on function public.foro_borrar_comentario(bigint) from public, anon, authenticated;
revoke all on function public.foro_reportar(bigint, bigint, text, text) from public, anon, authenticated;

-- Leer, también sin sesión: es lo que Google indexa (ver supabase/tests/permisos.sql).
grant execute on function public.foro_feed(text, text, bigint, integer) to anon, authenticated;
grant execute on function public.foro_publicacion(bigint) to anon, authenticated;
grant execute on function public.foro_tendencias() to anon, authenticated;
grant execute on function public.foro_mapa() to anon, authenticated;

grant execute on function public.foro_publicar(text, text, text, bigint, text, boolean) to authenticated;
grant execute on function public.foro_editar(bigint, text) to authenticated;
grant execute on function public.foro_borrar(bigint) to authenticated;
grant execute on function public.foro_votar(bigint, integer) to authenticated;
grant execute on function public.foro_confirmar(bigint, boolean) to authenticated;
grant execute on function public.foro_comentar(bigint, text, bigint, boolean) to authenticated;
grant execute on function public.foro_votar_comentario(bigint, integer) to authenticated;
grant execute on function public.foro_borrar_comentario(bigint) to authenticated;
grant execute on function public.foro_reportar(bigint, bigint, text, text) to authenticated;
