-- ============================================================================
-- La app por fin pregunta si el piloto consiguió el trabajo.
--
-- Todo lo que Aviatory mide se detiene justo antes de lo único que importa: si
-- el piloto entró o no a una aerolínea. Se sabe cuántas horas lleva, qué nivel
-- de inglés tiene y para cuál califica, y después nada. Eso deja tres agujeros:
--
--   - No hay razón de volver que no sea estudiar. El que ya se postuló y está
--     esperando respuesta no tiene nada que hacer en la app.
--   - No hay forma de saber si Aviatory sirve. La pregunta «¿ayudó esto a que
--     te contrataran?» no se le ha hecho nunca a nadie.
--   - El referido es un banner sin historia detrás. Pedirlo tiene sentido justo
--     cuando alguien acaba de entrar a una aerolínea, y ese momento hoy pasa
--     sin que la app se entere.
--
-- Esto es el registro del piloto sobre su propia búsqueda, no un dato
-- verificado. Si algún día se publica «N pilotos contratados», ese número
-- necesita otra cosa (una verificación como la de las horas): aquí un piloto
-- puede marcarse contratado y nadie lo comprueba. Está bien para lo que sirve
-- ahora, y queda dicho para que no se use como lo que no es.
--
-- No borra filas.
-- ============================================================================

do $bloque$
begin
  create type public.estado_postulacion as enum (
    'postulada',   -- mandó la hoja de vida
    'en_proceso',  -- lo llamaron: entrevista, simulador, exámenes
    'contratado',
    'no_quedo',
    'retirada'     -- se bajó él
  );
exception when duplicate_object then null;
end $bloque$;

-- En qué etapa se quedó, cuando no siguió. Es el dato más útil de todos: dice
-- qué piden de verdad las aerolíneas de la región, y contra eso se mide si los
-- módulos preparan para lo que hay que preparar.
do $bloque$
begin
  create type public.etapa_proceso as enum (
    'hoja_de_vida',
    'psicotecnicas',
    'entrevista',
    'simulador',
    'ingles',
    'medico',
    'otra'
  );
exception when duplicate_object then null;
end $bloque$;

create table if not exists public.postulaciones (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  -- La aerolínea de la lista, si está; si no, la escribe. Las aerolíneas de la
  -- tabla son seis y los pilotos se postulan a más.
  airline_id bigint references public.airlines (id),
  aerolinea text check (aerolinea is null or char_length(aerolinea) between 2 and 80),
  estado public.estado_postulacion not null default 'postulada',
  etapa_final public.etapa_proceso,
  nota text check (nota is null or char_length(nota) <= 500),
  postulada_en date not null default (now() at time zone 'America/Bogota')::date,
  creada_en timestamptz not null default now(),
  actualizada_en timestamptz not null default now(),
  constraint postulacion_con_aerolinea check (airline_id is not null or aerolinea is not null),
  -- La fecha no puede ser del futuro ni de antes de que existiera la aviación
  -- comercial en serio: un dedazo en el año se ve aquí y no en la pantalla.
  constraint postulacion_fecha_razonable check (postulada_en <= current_date and postulada_en >= date '2000-01-01')
);

comment on table public.postulaciones is
  'Lo que el piloto registra de su propia búsqueda de trabajo. No está verificado: es su relato.';
comment on column public.postulaciones.etapa_final is
  'Hasta dónde llegó cuando no siguió. Dice qué piden las aerolíneas de la región.';

-- Toda clave foránea lleva su índice.
create index if not exists postulaciones_user_idx
  on public.postulaciones (user_id, postulada_en desc);
create index if not exists postulaciones_airline_idx
  on public.postulaciones (airline_id);
-- Las abiertas, que son las que el recordatorio busca.
create index if not exists postulaciones_abiertas_idx
  on public.postulaciones (actualizada_en) where estado in ('postulada', 'en_proceso');

-- `actualizada_en` la pone la base y no el cliente: es lo que mide el
-- recordatorio, y si el cliente pudiera escribirla podría silenciarlo.
create or replace function private.tocar_postulacion()
returns trigger
language plpgsql
security definer
set search_path = ''
as $tocar$
begin
  new.actualizada_en := now();
  new.creada_en := coalesce(old.creada_en, new.creada_en);
  return new;
end;
$tocar$;

drop trigger if exists trg_tocar_postulacion on public.postulaciones;
create trigger trg_tocar_postulacion
  before insert or update on public.postulaciones
  for each row execute function private.tocar_postulacion();

alter table public.postulaciones enable row level security;
revoke all on table public.postulaciones from anon, authenticated;

drop policy if exists "postulaciones_select_own" on public.postulaciones;
create policy "postulaciones_select_own"
  on public.postulaciones for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "postulaciones_insert_own" on public.postulaciones;
create policy "postulaciones_insert_own"
  on public.postulaciones for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "postulaciones_update_own" on public.postulaciones;
create policy "postulaciones_update_own"
  on public.postulaciones for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- Solo lo que usan esas políticas, y por columna: el cliente no escribe
-- `actualizada_en` ni `creada_en`, que las pone el disparador.
grant select on table public.postulaciones to authenticated;
grant insert (user_id, airline_id, aerolinea, estado, etapa_final, nota, postulada_en)
  on table public.postulaciones to authenticated;
grant update (airline_id, aerolinea, estado, etapa_final, nota, postulada_en)
  on table public.postulaciones to authenticated;

-- Sin delete: una postulación que no fue se marca `retirada`, no se borra. Lo
-- que pasó en la carrera de alguien no se deshace.
