-- ============================================================================
-- Errores del cliente: lo que falla en el navegador del piloto llega a la base.
--
-- Hallazgo de la segunda auditoría: los fallos de producción solo quedaban en la
-- consola del navegador de cada piloto. Una pantalla que se cae, un progreso que
-- no se guarda o una respuesta del servidor con otra forma no los veía nadie.
--
-- Cambios:
--   1. errores_cliente: contexto, mensaje, detalle (la traza), ruta, versión de
--      la app y navegador, por piloto. Sin permisos para el cliente: la escribe
--      solo la función y se lee desde el panel de Supabase.
--   2. reportar_error_cliente(): recorta cada campo y aplica un tope de 30
--      reportes por piloto por hora. Pasado el tope no escribe y responde false.
--
-- Los errores sin sesión (la portada, el registro) no se guardan: sin piloto no
-- hay tope por usuario, y un tope global dejaría llenar la tabla a cualquiera.
--
-- No toca filas existentes.
-- ============================================================================

create table if not exists public.errores_cliente (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  creado_en timestamptz not null default now(),
  contexto text not null check (char_length(contexto) between 1 and 120),
  mensaje text not null check (char_length(mensaje) between 1 and 1000),
  detalle text check (char_length(detalle) <= 4000),
  ruta text check (char_length(ruta) <= 300),
  version_app text check (char_length(version_app) <= 40),
  navegador text check (char_length(navegador) <= 300)
);

comment on table public.errores_cliente is
  'Errores que reporta la app desde el navegador del piloto (src/lib/errores.ts). La escribe solo reportar_error_cliente; el cliente no la lee.';

alter table public.errores_cliente enable row level security;
revoke all on table public.errores_cliente from anon, authenticated;

-- El tope cuenta por piloto y fecha; la revisión lee los más recientes.
create index if not exists errores_cliente_user_creado_idx on public.errores_cliente (user_id, creado_en desc);
create index if not exists errores_cliente_creado_idx on public.errores_cliente (creado_en desc);

create or replace function public.reportar_error_cliente(
  p_contexto text,
  p_mensaje text,
  p_detalle text default null,
  p_ruta text default null,
  p_version text default null,
  p_navegador text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'sin_sesion' using errcode = '42501';
  end if;
  if nullif(trim(p_contexto), '') is null or nullif(trim(p_mensaje), '') is null then
    raise exception 'reporte_vacio' using errcode = '22023';
  end if;

  -- El candado serializa los reportes del mismo piloto: sin él, una ráfaga en
  -- paralelo leería el mismo conteo y pasaría el tope junta.
  perform pg_advisory_xact_lock(hashtextextended('errores_cliente:' || v_user::text, 0));
  if (
    select count(*) from public.errores_cliente e
    where e.user_id = v_user and e.creado_en > now() - interval '1 hour'
  ) >= 30 then
    return false;
  end if;

  insert into public.errores_cliente (user_id, contexto, mensaje, detalle, ruta, version_app, navegador)
  values (
    v_user,
    left(trim(p_contexto), 120),
    left(p_mensaje, 1000),
    left(p_detalle, 4000),
    left(p_ruta, 300),
    left(p_version, 40),
    left(p_navegador, 300)
  );
  return true;
end
$$;

revoke all on function public.reportar_error_cliente(text, text, text, text, text, text) from public, anon;
grant execute on function public.reportar_error_cliente(text, text, text, text, text, text) to authenticated;
