-- ============================================================================
-- Módulo Inglés ICAO — vocabulario consultable + banco de quiz + entrevista
-- ============================================================================
-- 1) Glosario público (icao_vocabulary): ~350 términos del libro ICAO Vocab Book
--    de Cami. No es competitivo (libro estándar de aviación), va sin encriptar
--    para permitir búsqueda full-text rápida.
-- 2) Banco de preguntas vocabulario/comprensión (icao_quiz_questions): MC
--    simples derivadas del glosario. Tampoco se encriptan (no son del banco
--    oficial — son material pedagógico estándar).
-- 3) Nueva categoría 'intro_speaking' en interview_sim_categories +
--    ~15 preguntas que toda aerolínea pide para evaluar fluidez en speaking.
-- ============================================================================

-- ───────────────────────────────────────────────────────────────────────────
-- VOCABULARIO
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.icao_vocabulary (
  id bigint generated always as identity primary key,
  term_en text not null,
  translation_es text not null,
  definition text not null,
  category text not null default 'flight_ops'
    check (category in ('aircraft','airport','navigation','flight_ops','weather','health','security','non_routine')),
  example text,
  audio_url text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create unique index if not exists uq_icao_vocabulary_term on public.icao_vocabulary(lower(term_en));
create index if not exists idx_icao_vocabulary_category on public.icao_vocabulary(category) where is_active;
create index if not exists idx_icao_vocabulary_search
  on public.icao_vocabulary using gin (to_tsvector('simple', term_en || ' ' || translation_es || ' ' || definition))
  where is_active;

alter table public.icao_vocabulary enable row level security;
create policy "icao_vocabulary_read" on public.icao_vocabulary for select to authenticated using (is_active);

-- ───────────────────────────────────────────────────────────────────────────
-- QUIZ — preguntas de comprensión / vocabulario (no encriptadas, públicas
-- al authenticated)
-- ───────────────────────────────────────────────────────────────────────────
create table if not exists public.icao_quiz_questions (
  id bigint generated always as identity primary key,
  topic text not null default 'vocabulary'
    check (topic in ('vocabulary','comprehension','phraseology','emergencies','weather','medical','security','technical')),
  prompt text not null,                  -- el enunciado de la pregunta
  context text,                          -- opcional: contexto/escenario antes de la pregunta
  options jsonb not null,                -- {"a":"...","b":"...","c":"...","d":"..."}
  correct_answer text not null check (correct_answer in ('a','b','c','d')),
  explanation text,                      -- explicación breve para feedback
  difficulty smallint default 2 check (difficulty between 1 and 5),
  related_vocab text[] default '{}',     -- términos del glosario relacionados
  is_active boolean default true,
  created_at timestamptz default now()
);

create index if not exists idx_icao_quiz_topic on public.icao_quiz_questions(topic) where is_active;

alter table public.icao_quiz_questions enable row level security;
create policy "icao_quiz_questions_read" on public.icao_quiz_questions for select to authenticated using (is_active);

-- Tracking de intentos por usuario
create table if not exists public.user_icao_quiz_attempts (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.icao_quiz_questions(id) on delete cascade,
  answer text not null check (answer in ('a','b','c','d')),
  is_correct boolean not null,
  attempted_at timestamptz default now()
);

create index if not exists idx_user_icao_quiz_user on public.user_icao_quiz_attempts(user_id, attempted_at desc);

alter table public.user_icao_quiz_attempts enable row level security;
create policy "user_icao_quiz_own" on public.user_icao_quiz_attempts for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ───────────────────────────────────────────────────────────────────────────
-- ENTREVISTA: nueva categoría 'intro_speaking' (evaluación oral genérica)
-- ───────────────────────────────────────────────────────────────────────────
insert into public.interview_sim_categories (slug, name, type, description, icon_name, color, order_index) values
  ('intro_speaking', 'Intro Speaking', 'hr', 'Las preguntas básicas que toda aerolínea hace al inicio para evaluar tu fluidez y capacidad de respuesta. Si fallás acá, no pasás al técnico.', 'Mic', 'amber', 5)
on conflict (slug) do nothing;

insert into public.interview_sim_questions (category_id, slug, question_text, intent, expected_topics, follow_ups, ideal_duration_seconds, difficulty, order_index)
select c.id, slug, question_text, intent, expected_topics::jsonb, follow_ups::jsonb, dur, diff, ord
from public.interview_sim_categories c, (values
  ('intro_speaking_tell_about_yourself',
   'Tell me about yourself.',
   'La pregunta más común del mundo. Mide: capacidad de armar una historia coherente en 90s, priorización, y si sos profesional. Estructura sugerida: presente (qué hacés ahora) → pasado (cómo llegaste acá) → futuro (qué buscás).',
   '["nombre y rol actual","background aeronáutico","motivación para aerolínea","qué buscás en esta posición"]',
   '["What did you like most about your last job?","Why did you choose aviation?"]',
   90, 2, 10),

  ('intro_speaking_why_pilot',
   'Why did you decide to become a pilot?',
   'Mide pasión genuina vs respuesta de manual. Las mejores respuestas son específicas (una experiencia concreta) no genéricas ("siempre me gustaron los aviones").',
   '["momento detonante","qué te mantiene motivado","sacrificios que hiciste"]',
   '["Tell me about your first flight.","What would you do if you couldn''t fly anymore?"]',
   90, 2, 20),

  ('intro_speaking_why_this_airline',
   'Why do you want to work for our airline specifically?',
   'Mide preparación. Si decís lo mismo que dirías de cualquier otra aerolínea, perdés. Hacé homework: flota, rutas, cultura, expansión reciente.',
   '["aspecto específico de la aerolínea","alineación con tus valores/objetivos","qué aportarías"]',
   '["What do you know about our fleet?","Who do you think is our main competitor?"]',
   60, 3, 30),

  ('intro_speaking_strengths_weaknesses',
   'What are your main strengths and weaknesses?',
   'Strengths: relevantes al rol (CRM, calma bajo presión, atención al detalle). Weaknesses: real pero con acción concreta para mejorarla. NUNCA "soy perfeccionista".',
   '["2 strengths relevantes con ejemplo","1 weakness real","plan de acción para esa weakness"]',
   '["Can you give me an example of that strength in action?","How are you working on improving that weakness?"]',
   90, 3, 40),

  ('intro_speaking_challenging_situation',
   'Tell me about a challenging situation you had to handle, and how you resolved it.',
   'STAR: Situation, Task, Action, Result. Aerolíneas buscan: que tomaste acción, que aprendiste algo, que no echás la culpa a otros.',
   '["situación clara","tu rol específico","acciones que tomaste","resultado medible","aprendizaje"]',
   '["What would you do differently next time?","How did you communicate with your team during that?"]',
   120, 3, 50),

  ('intro_speaking_pressure',
   'How do you handle pressure or stressful situations?',
   'No digas "no me estreso" — eso es red flag. Mostrá una estrategia concreta + un ejemplo. Bonus: vinculá con safety y decision making en cockpit.',
   '["estrategia concreta","ejemplo específico","cómo afecta tu performance","vínculo con cockpit/operación"]',
   '["Tell me about a time you made a decision under pressure.","How do you prevent stress from accumulating?"]',
   90, 3, 60),

  ('intro_speaking_teamwork',
   'Describe a time you worked as part of a team to achieve a goal.',
   'CRM puro. Buscan: comunicación, contribución específica, manejo de conflicto, rol claro. Si volás en cabina, lo viviste 100 veces.',
   '["rol del equipo y tuyo","cómo se comunicaron","conflicto y resolución","resultado"]',
   '["What was your specific contribution?","What did you learn about teamwork?"]',
   90, 2, 70),

  ('intro_speaking_leadership',
   'Tell me about a time you had to lead others.',
   'No necesitás ser jefe — capitán de equipo, instructor de nuevos, líder de un proyecto. Mide: iniciativa, manejo de personas, accountability.',
   '["contexto","decisión que tomaste","cómo influiste en otros","resultado"]',
   '["How did you handle disagreement?","Looking back, what would you do differently?"]',
   90, 3, 80),

  ('intro_speaking_failure',
   'Tell me about your biggest failure and what you learned from it.',
   'Trampa común: decir "no he fracasado". Mostrar vulnerabilidad real + aprendizaje + cómo aplicás esa lección hoy. Eso es maduez profesional.',
   '["fracaso real","tu responsabilidad (no echar culpas)","aprendizaje concreto","aplicación posterior"]',
   '["How did you recover?","Would you take that risk again?"]',
   120, 4, 90),

  ('intro_speaking_5_years',
   'Where do you see yourself in 5 years?',
   'Quieren ver que esta posición es un paso lógico en tu carrera, no un trampolín a otra cosa. Ambición sí, pero alineada con la aerolínea.',
   '["progresión natural en la aerolínea","habilidades que querés desarrollar","compromiso con la empresa"]',
   '["What if there''s no upgrade in 5 years?","How does this role fit your plan?"]',
   60, 2, 100),

  ('intro_speaking_why_hire_you',
   'Why should we hire you over the other candidates?',
   'Sin arrogancia, sin falsa modestia. Listá 2-3 cosas concretas que aportás (experiencia específica, certificaciones, soft skills demostradas con ejemplo).',
   '["2-3 diferenciadores concretos","ejemplo respaldando cada uno","fit con cultura/operación"]',
   '["Why not the others?","What would you bring in your first 90 days?"]',
   90, 3, 110),

  ('intro_speaking_motivation',
   'What motivates you in your daily work?',
   'Auto-conocimiento. Tres niveles válidos: el reto técnico, la responsabilidad por los pax, el desarrollo continuo. Evitá decir "el dinero".',
   '["motivador interno claro","cómo se manifiesta en tu día a día","ejemplo concreto"]',
   '["What demotivates you?","What kept you going through tough training?"]',
   60, 2, 120),

  ('intro_speaking_conflict',
   'Tell me about a time you had a conflict with a coworker. How did you resolve it?',
   'CRM directo. Buscan: comunicación asertiva, escucha activa, foco en el problema (no la persona), resolución sin escalada innecesaria.',
   '["situación neutral (no demonizar al otro)","cómo abriste la conversación","escucha","solución acordada"]',
   '["What if the other person hadn''t cooperated?","How do you prevent these conflicts?"]',
   120, 4, 130),

  ('intro_speaking_describe_yourself_3_words',
   'If you had to describe yourself in three words, which would they be and why?',
   'Pregunta de calentamiento que dice mucho. Elegí palabras que apoyen tu candidatura (no "fun, creative, friendly" — sí "disciplined, calm, methodical"). Justifica cada una con un mini-ejemplo.',
   '["3 adjetivos profesionales","justificación con ejemplo para cada uno","coherencia con el rol"]',
   '["Which of those three is your strongest?","Which one would your last captain pick?"]',
   60, 2, 140),

  ('intro_speaking_questions_for_us',
   'Do you have any questions for us?',
   'NUNCA digas "no, está todo claro". Mostrar interés con 2-3 preguntas inteligentes: cultura, próximos pasos del proceso, expectativas en los primeros 6 meses. Evitá preguntas sobre sueldo o vacaciones en esta etapa.',
   '["2-3 preguntas preparadas","mostrar interés genuino","preguntas sobre rol/cultura/desarrollo","cierre profesional"]',
   '["What attracted you to ask that?"]',
   45, 2, 150)
) as q(slug, question_text, intent, expected_topics, follow_ups, dur, diff, ord)
where c.slug = 'intro_speaking'
on conflict (slug) do nothing;

-- ───────────────────────────────────────────────────────────────────────────
-- PREGUNTAS DE QUIZ — vocabulario y comprensión (derivadas del libro de Cami)
-- ───────────────────────────────────────────────────────────────────────────
insert into public.icao_quiz_questions (topic, prompt, context, options, correct_answer, explanation, difficulty, related_vocab) values
  ('vocabulary',
   'The cabin crew reported an UNRULY passenger in the aft cabin. What does "unruly" mean?',
   null,
   '{"a":"Aggressive, belligerent, out of control","b":"Sleeping deeply","c":"Asking too many questions","d":"Drunk but cooperative"}',
   'a',
   '"Unruly" describes a passenger that is aggressive, belligerent or out of control. It does NOT necessarily mean drunk (that would be "inebriated/intoxicated").',
   2, ARRAY['unruly','aft']),

  ('vocabulary',
   'In aviation, what is the AFT of the aircraft?',
   null,
   '{"a":"The forward section, near the cockpit","b":"The back part of the plane (same as ''rear'')","c":"The wing area","d":"The cargo hold below the cabin"}',
   'b',
   'Aft is an adjective for the back/rear part of the plane. Avoid using "before/after" in aviation for position — those refer to time.',
   1, ARRAY['aft']),

  ('vocabulary',
   '"Number 2 engine INGESTED some birds during climb-out." What happened?',
   null,
   '{"a":"The engine ate fuel too fast","b":"Birds were sucked into the engine","c":"The engine overheated","d":"Birds hit the windshield"}',
   'b',
   'To ingest = to suck or pull into. Bird ingestion is a classic engine event (e.g. USAir 1549 / Hudson).',
   1, ARRAY['ingest','ingested a bird','bird strike']),

  ('vocabulary',
   'You hear: "We have 3 passengers suffering from severe CONCUSSION and bruises from the turbulence." What is a concussion?',
   null,
   '{"a":"A skin burn","b":"A blow to the head causing brain trauma","c":"Bleeding in the chest","d":"An allergic reaction"}',
   'b',
   'Concussion = a blow to the head / brain trauma. Common in unsecured passengers during severe turbulence.',
   2, ARRAY['concussion','severe','turbulence']),

  ('comprehension',
   'ATC says: "Maintain FL310, expect onward clearance at time 25." What does "onward clearance" mean?',
   null,
   '{"a":"A clearance to descend immediately","b":"A clearance to continue your route after a waypoint or hold","c":"A new transponder code","d":"Permission to land"}',
   'b',
   'Onward clearance = the next clearance to pursue the flight after a waypoint or holding action.',
   3, ARRAY['onward clearance','clearance']),

  ('phraseology',
   'In standard ICAO phraseology, which phrase should be used instead of the ambiguous "Go ahead"?',
   null,
   '{"a":"Continue","b":"Pass your message","c":"Roger that","d":"Affirmative"}',
   'b',
   '"Go ahead" can mean either "move forward" or "say your message" — ICAO replaced it with the unambiguous "Pass your message".',
   2, ARRAY['pass your message','go ahead']),

  ('phraseology',
   '"Roger" in radiotelephony means:',
   null,
   '{"a":"Yes, I agree","b":"I have received all your last transmission","c":"No, negative","d":"I will comply"}',
   'b',
   'Roger only means "received". It is NOT a valid reply to a yes/no question and is NOT a readback. For yes use "Affirm", for compliance use "Wilco".',
   2, ARRAY['roger','read back']),

  ('weather',
   '"Be advised, there is STANDING WATER on Runway 27R, braking action POOR." What is the main risk?',
   null,
   '{"a":"Tires deflating","b":"Aquaplaning and extended landing distance","c":"Engine ingestion of water","d":"Increased fuel burn"}',
   'b',
   'Standing water + poor braking action = aquaplaning risk and longer stopping distance. May force a diversion or longer runway.',
   3, ARRAY['standing water','braking action','aqua planed']),

  ('weather',
   'Which of these is NOT a way to describe turbulence?',
   null,
   '{"a":"Bumpy","b":"Light chop","c":"Choppy","d":"Frosty"}',
   'd',
   '"Frosty" describes cold/ice on a surface. Turbulence: bumpy, choppy, light chop, smooth, severe.',
   2, ARRAY['bumpy','light chop','severe turbulence']),

  ('weather',
   'A SHIFT in the wind means:',
   null,
   '{"a":"The wind has stopped","b":"A change in wind direction","c":"The wind is becoming stronger","d":"Crosswind component is zero"}',
   'b',
   'Shift = change of wind direction. Increasing/decreasing wind is "strengthening/weakening" or "gusting".',
   2, ARRAY['shift','gusty','wind shear']),

  ('medical',
   'A passenger had a FIT. What happened?',
   null,
   '{"a":"They lost their luggage","b":"They had an acute attack (often epileptic seizure)","c":"They became angry and disruptive","d":"They got airsick"}',
   'b',
   'A fit = an acute attack, usually epileptic (seizure). Can also be "a fit of coughing" or "a fit of anger" depending on context.',
   2, ARRAY['fit','seizure','have a fit']),

  ('medical',
   'In the medical context, INCAPACITATED means:',
   null,
   '{"a":"Tired but functional","b":"Unconscious or too ill to function properly","c":"Slightly injured","d":"Annoyed"}',
   'b',
   'Incapacitated = the person cannot perform their duties (e.g. Captain incapacitated due to a stroke).',
   3, ARRAY['incapacitated','unconscious']),

  ('medical',
   'You need urgent medical help on board. Which is the standard call?',
   null,
   '{"a":"Call airline marketing","b":"Request medical assistance on arrival / Contact MedLink","c":"Declare a Mayday immediately even if not life-threatening","d":"Ask the flight attendant to do CPR on every passenger"}',
   'b',
   'Standard escalation: assess → request medical assistance on arrival / contact MedLink or MedAire → if life-threatening, declare emergency and divert.',
   3, ARRAY['medical team','contact medlink','first aid']),

  ('security',
   'A passenger is INEBRIATED. They are:',
   null,
   '{"a":"Sleeping","b":"Drunk / under the effect of alcohol","c":"Disabled","d":"Coughing blood"}',
   'b',
   'Inebriated = drunk. Note the distinction: intoxicated may include drugs; inebriated is alcohol-specific.',
   1, ARRAY['inebriated','intoxicated','unruly']),

  ('security',
   'The flight attendant said the passenger had to be RESTRAINED. What happened?',
   null,
   '{"a":"He was given a free upgrade","b":"He was physically held / immobilised because of violent behavior","c":"He was given oxygen","d":"He was moved to first class"}',
   'b',
   'To restrain = to physically hold/immobilise (often with plasticuffs/handcuffs) when a passenger is violent or refuses to cooperate.',
   2, ARRAY['restrained','unruly','handcuffs']),

  ('emergencies',
   '"The engine had a FLAMEOUT during climb." What does flameout mean?',
   null,
   '{"a":"The engine caught external fire","b":"A loss of combustion in a gas turbine engine","c":"A fuel leak","d":"A bird strike on the cowling"}',
   'b',
   'Flameout = loss of combustion in the engine. Often caused by bird ingestion, fuel starvation, or volcanic ash.',
   3, ARRAY['flameout','flame out','ingested a bird']),

  ('emergencies',
   'The crew DITCHED the aircraft. They:',
   null,
   '{"a":"Landed at an alternate airport","b":"Performed a controlled landing on water in an emergency","c":"Aborted takeoff","d":"Rejected a clearance"}',
   'b',
   'Ditching = controlled emergency landing on water (e.g. US Air 1549 on the Hudson).',
   2, ARRAY['ditching','escape slide']),

  ('emergencies',
   'The cabin crew DEPLOYED the chute. What did they do?',
   null,
   '{"a":"Closed and locked all the doors","b":"Inflated and used the escape slide for evacuation","c":"Turned off the cabin lights","d":"Distributed life jackets"}',
   'b',
   'Chute = escape slide (rapid-inflation). Deploy = activate/inflate it.',
   1, ARRAY['chute','escape slide','evacuation']),

  ('technical',
   'The circuit breaker has TRIPPED. What does that mean?',
   null,
   '{"a":"It activated automatically because of an electrical fault","b":"It was manually switched off by the crew","c":"It melted","d":"It was disconnected from the panel"}',
   'a',
   'A tripped circuit breaker has opened the circuit automatically because of overload/short. Reset it by pressing it back in (only if procedure allows).',
   2, ARRAY['tripped','circuit breaker','reset']),

  ('technical',
   '"The slats appear to be JAMMED in the 15-degree position." What does jammed mean?',
   null,
   '{"a":"Working normally","b":"Blocked in position, unable to move","c":"Retracted fully","d":"Vibrating"}',
   'b',
   'Jammed = blocked / stuck in a position. Used a lot about flaps, slats, servocontrols, microphones, etc.',
   2, ARRAY['jammed','stuck','seize']),

  ('technical',
   '"The right hand windshield is slightly CRACKED." What is the correct pronunciation and meaning?',
   null,
   '{"a":"Pronounced ''crak-ed''. Means broken in pieces.","b":"Pronounced ''crackt''. Means damaged with small fissures (still intact).","c":"Pronounced ''krash-ed''. Means shattered.","d":"Pronounced ''cracket''. Means scratched on the surface."}',
   'b',
   'Pronunciation is "crackt" (one syllable). Cracked = with fissures but not shattered (which would be much worse).',
   3, ARRAY['cracked','shattered','windshield']),

  ('phraseology',
   'In ICAO English, the decimal point is read as:',
   null,
   '{"a":"Point","b":"Decimal","c":"Dot","d":"Comma"}',
   'b',
   'ICAO uses "decimal" (e.g. 121 decimal 5). FAA uses "point". On exam day stick with ICAO.',
   2, ARRAY['decimal','point']),

  ('phraseology',
   'You hear "Squawk Charlie". The pilot must:',
   null,
   '{"a":"Switch transponder to mode C (altitude reporting)","b":"Switch to standby","c":"Squawk 7700 (emergency)","d":"Turn off the transponder"}',
   'a',
   '"Squawk Charlie" = activate altitude reporting (Mode C). Also seen as "Squawk altitude".',
   3, ARRAY['squawk altitude','squawk charlie']),

  ('comprehension',
   '"All flights are delayed DUE TO heavy fog at the destination." DUE TO means:',
   null,
   '{"a":"On the way to","b":"Because of","c":"On time","d":"In spite of"}',
   'b',
   '"Due to" / "because of" / "caused by" all express cause. Useful glue word in cause-effect reporting.',
   1, ARRAY['due','caused by']),

  ('comprehension',
   'A "PRECAUTIONARY LANDING" is:',
   null,
   '{"a":"An emergency landing where Mayday is declared","b":"An anticipated landing to manage an abnormal situation, but NOT an emergency","c":"A scheduled landing at the destination","d":"A go-around"}',
   'b',
   'Precautionary landing = the crew decides to land early because of an abnormal situation (technical, medical), but it is not (yet) an emergency. Different from a Mayday/emergency landing.',
   3, ARRAY['precautionary landing','divert']),

  ('comprehension',
   'The First Officer noticed on WALK AROUND that the cowl panel looked LOOSE. They should:',
   null,
   '{"a":"Ignore it and depart on time","b":"Report it to engineering before departure","c":"Wait until cruise to check","d":"Disable the engine"}',
   'b',
   'Walk around = external pre-flight inspection. A loose cowl panel is a no-go item and must be reported to engineering / maintenance.',
   2, ARRAY['walk around inspection','loose','cowl panel']),

  ('weather',
   'WIND SHEAR is dangerous because it:',
   null,
   '{"a":"Causes the cabin to depressurize","b":"Causes a sudden change in airspeed/altitude, especially close to the ground","c":"Reduces fuel flow","d":"Damages the radome"}',
   'b',
   'Wind shear = sudden change in wind speed/direction. Critical near takeoff/landing. Modern aircraft have wind shear warnings + recovery procedures.',
   3, ARRAY['wind shear','undershoot windshear','downdraught']),

  ('vocabulary',
   'You hear: "We need to DUMP 2 tonnes of fuel." Why?',
   null,
   '{"a":"To reduce weight below Maximum Landing Weight before an emergency landing","b":"To clean the tanks","c":"To increase climb performance","d":"To save fuel for the next flight"}',
   'a',
   'Dump (or jettison) fuel = discharge fuel in flight to bring weight below MLW before a precautionary/emergency landing.',
   3, ARRAY['dump','jettison']),

  ('vocabulary',
   'A passenger is reported as BLEEDING heavily. The crew should:',
   null,
   '{"a":"Ignore until landing","b":"Apply first aid, contact MedLink, consider diversion","c":"Move them to first class","d":"Give them food"}',
   'b',
   'Standard response: first aid → contact ground medical (MedLink/MedAire) → assess if diversion needed.',
   2, ARRAY['bleeding','first aid','medical team']),

  ('comprehension',
   'The taxiing aircraft is reported as BOGGED DOWN off Taxiway Lima. What does that mean?',
   null,
   '{"a":"Flying low and slow","b":"Stuck in mud, wet earth or sand","c":"Out of fuel","d":"In a holding pattern"}',
   'b',
   'Bogged down = stuck in mud/sand. Typical for a runway excursion or after leaving the paved surface. Tug needed.',
   2, ARRAY['bogged down','mud','stuck','tug'])
on conflict do nothing;

-- ───────────────────────────────────────────────────────────────────────────
-- SEED VOCABULARY (~350 términos del libro ICAO Vocab Book)
-- ───────────────────────────────────────────────────────────────────────────
insert into public.icao_vocabulary (term_en, translation_es, definition, category) values
  ('aft','atrás','an adjective referring to the back part of a plane. Rear is also used with the same meaning. It contrasts with forward. The words before and after are only used to talk about time relationships. There is smoke coming from the aft of the cabin','non_routine'),
  ('abeam the runway','relativo a 90 grados','indicating that the runway is to the side of the aircraft, at a bearing of approximately 90° or 270° relative to the aircraft, i.e. to the right or the left','airport'),
  ('accretion rate','la velocidad en que el hielo se acumula','the speed at which ice is accumulating; it is also referred to as the accumulation rate or build-up rate. There is some accretion of ice on the leading edges of the wings and we need to de-ice before takeoff.','weather'),
  ('acrid','penetrante','used to describe a sharp, bitter (smell), especially of smoke or fumes: there was an acrid smell coming from the rear of the plane.','non_routine'),
  ('airstairs','escaleras','mobile stairs used at outlying stands for passengers to board and disembark: the jet way is inop so we will need airstairs to disembark the pax','airport'),
  ('baggage','equipage','small towed vehicle for transporting baggage: Some of the passenger baggage was missing and caused a delay','flight_ops'),
  ('belt conveyor- belt loader','banda de equipaje','baggage loader with rotating rubber belt used to load the bulk cargo compartment, hold 5','flight_ops'),
  ('blank','quedar en blanco','to stop displaying data, to become dark: the power failure caused the First Officer´s screen to blank momentarily','flight_ops'),
  ('blast fence','barrera defense/seguridad','long barrier which diverts efflux behind parked or taxiing aircraft:','flight_ops'),
  ('board','abordo','to go on the aircraft, to enplane: The passengers are boarding from Gate 27.','airport'),
  ('bogged down','atascarse','stuck in the mud, damp earth or sand: a tug is required to tow the Regional Jet which is bogged down off Taxiway Lima.','airport'),
  ('bomb scare','aviso de bomba','threat or fear that there may be a bomb on a plane or on the ground bomb warning a threat of a bomb on board or on the ground; a bomb scare. Even bomb scares which do not seem credible have to be taken seriously and the aircraft must divert and land as soon as possible. Sometimes also referred to as a bomb threat','security'),
  ('bound for','en ruta hacia','flying to: Air India 389 is bound for Dubai or enroute','flight_ops'),
  ('bowser','tanqueo por presion','Vehicle which pumps fuel from an underground fuel distribution system. Aircraft are refuelled either by tankers or bowsers.','aircraft'),
  ('bumpy','turbulencia','Turbulent, rough we are having a bumpy (rough/turbulent) ride at our present level','weather'),
  ('calm','calmarse','Quiet weather The wind is calm. El viento calmado hace que el ambiente sea agradable. The wind calmed as the hurricane moved off. El viento se calmó cuando el huracán pasó.','weather'),
  ('calm down','relajarse, tranquilizarse','Relax, take it easy ¡Ya no pasó nada malo, relajarse! Try to calm down the angry passenger','flight_ops'),
  ('chocks','tacos – cuňas','rubber or wooden blocks placed against the aircraft wheels to prevent aircraft movement: Are the chocks in place?','flight_ops'),
  ('chute','tobogán de evacuación','a rapid-inflation pneumatic channel to enable passengers and crew to evacuate quickly, it is also referred to as an escape slide. The cabin crew deployed the emergency slide/chute to evacuate the aircraft quickly.','non_routine'),
  ('circuit breaker','circuitos de protección electrica','an electrical protecting safety device which opens a circuit in case of an excessive flow of current. Most circuit breakers are located on the cockpit overhead panel and rear cockpit bulkhead. Reset tripped circuit breaker by turning power switch on. The circuit breaker was tripped','aircraft'),
  ('clogged','impedimentar, atascar','A blockage, to obstruct or become obstructed with thick or sticky matter. The fuel pipes were clogged-blocked with dirty fuel and needed cleaning','aircraft'),
  ('concise','conciso','short, efficient, not wasteful, not containing unnecessary information. Being concise is essential in radio communications, because pilots and ATCOs often have to communicate information fast','flight_ops'),
  ('conflicting','conflicto de trafico','traffic at or near the same flight level heading towards each other: there is conflicting traffic ahead, take avoiding action','navigation'),
  ('correction','corrección','phraseology which indicates that an error has been made by the person making the transmission and that correct information will follow: Climb to reach Flight Level 290 at time 58. Correction at time 55.','navigation'),
  ('cowl panel','parte de la nacela','part of the engine cowling – the fairing which surrounds and protects the engine and provides an optimum aerodynamic profile','aircraft'),
  ('crabbing','deriva','flying with drift due to crosswind: the aircraft was drifting (crabbing) to the side','weather'),
  ('cracked','fisura','damaged with small fissures: the right hand windshield appears to be slightly cracked','aircraft'),
  ('crane','grúa','a device for lifting and moving heavy objects, typically consisting of a moving boom, beam, or gantry from which lifting gear is suspended See also gantry.','flight_ops'),
  ('customer service manager','jefe de cabina','the chief cabin attendant on board a large aircraft – also known as the “Purser” on medium sized aircraft.','aircraft'),
  ('damper','amortiguador','a hydraulic shock absorber','aircraft'),
  ('deal with','lidiar con –dar solución','Handle, manage, address, resolve. You deal with the problem, I´ll fly the plane. The problem was brought to my attention and I dealt with it. Tuve que lidiar con el problema antes de que pasara a mayores','flight_ops'),
  ('debris','partes-pedazos de ..','the general name for objects which are where they shouldn’t be: Debris on the ground can be extremely dangerous for aircraft. There is debris at the far end of Runway 27R','airport'),
  ('decrab','corregir deriva','to re-align the aircraft on the runway centreline in crosswind conditions immediately before touchdown','weather'),
  ('de-energize','decenergizar','to remove electrical power, to switch off: We have a short circuit in the washroom smoke detector, we need to de-energise that circuit.','non_routine'),
  ('deflect','deflector','to move along a pre-defined arc: the rudder deflects','aircraft'),
  ('degradation','degradación','worsening: there has been a degradation in our roll control; the spoilers are responding more slowly.','aircraft'),
  ('degraded mode','reducer capacidad o modo degradado','in degraded mode means operating at a reduced capacity or in a mode with fewer capabilities: the ILS was operating in degraded mode','navigation'),
  ('dent','abolladura / mellar','Cause an inundation in metal The hailstones made dents in the roof of the car. Ese cuchillo está mellado.','weather'),
  ('deteriorate','deteriorado','become progressively worse. The passenger’s condition is deteriorating; we will need a priority landing','flight_ops'),
  ('discretion','según a uno le parezca mejor o su discreción','‘at your discretion’: timing or navigation is to be decided by the pilot','flight_ops'),
  ('disengage','desenganchar','to de-activate or place in neutral an automatic function; it may, however, remain armed. i.e. ready to operate: you can disengage the autopilot by using the IDPB','flight_ops'),
  ('disorientation','desorientación','loss of a sense of one’s position in space: the passenger was feeling disorientated after the bag fell on his head.','flight_ops'),
  ('dispatch','despacho','the airport service which is responsible for liaising with the crew about operational matters: ask Dispatch for an updated weight and balance sheet the Flight Ops department of an airline which plans and monitors each flight and provides operational information in abnormal situations: when the flight crew encountered volcanic ash they contacted their company dispatch','airport'),
  ('dispatcher','despachador','the airport agent who provides the weight and balance sheet which must be checked and signed by the captain. The weight and balance sheet contains updated information about the aircraft payload (passengers, baggage, cargo and fuel) and its location. This allows the aircraft’s centre of gravity, which must be within certain limits for safe take-off and flight, to be calculated','airport'),
  ('disregard','omitir- ignorar','to decide not to comply with or ignore an instruction, information or recommendation etc. Flight crews may disregard controller instructions in certain situations, for example to resolve a TCAS Resolution Advisory.','navigation'),
  ('distraction','distracción','something which disturbs mental concentration and attention a cabin attendant entering the flightdeck when crew workload is high will be a distraction','aircraft'),
  ('ditching','acuatizar','alighting on water in an emergency: the successful ditching in the Hudson River of US Air 1549 has become famous in aviation history','non_routine'),
  ('diverging','cambiar','moving or heading in two different directions','navigation'),
  ('divert','desviar','to make a change in the flight plan, often to fly to an alternate destination;','flight_ops'),
  ('don','colocarse- usar','to put on a mask or life vest: in the event of smoke in the cockpit the flight crew are advised to don their oxygen masks','non_routine'),
  ('dot','punto','point on the localizer and glideslope scales which indicates the degree of deviation left or right / above or below during approach','navigation'),
  ('downgrade','operación reducida- degradado','reduced operation – the ILS is operating in downgraded mode','navigation'),
  ('downwind','con el viento','in a direction away from the source of the wind, 180° from the landing direction: the pilot is flying the downwind leg and is about to make the base turn','flight_ops'),
  ('drainage','drenador/sistema de drenaje','grate metal grills on ground to evacuate rain water The drainage metal grills are blocked and the runway is flooded','non_routine'),
  ('drift','corregir','gradual lateral movement off course usually caused by a crosswind (also known as “crabbing”','weather'),
  ('drifting snow DRSN','nieve acumulada','snow that has been blown by the wind to form a deep deposit- Snow has drifted onto Runway 27R and we are waiting for the snow plough to clear it.','airport'),
  ('drive motor','motor electric','an electrical motor which moves containers etc. into position. The electrical drive motor that moves the pilot’s seat appears to be inoperative','flight_ops'),
  ('drizzle DZ','llovisna','very light but constant rain. The airport was covered with a cloud of drizzle','weather'),
  ('drop','caer','to decrease, to go down: the oil pressure is dropping','flight_ops'),
  ('due','debido a – a razón de','used as a preposition meaning due to / because of: all departures are delayed due to heavy fog The flight was delayed due to bad weather – El Vuelo retrasó el inicio del partido debido al mal tiempo.','weather'),
  ('dump','votar- vaciar','to discharge fuel in flight in order to reduce the aircraft’s weight; to jettison: we are over our MLW (Maximum Landing Weight) and need to dump 2 tonnes of fuel','aircraft'),
  ('dutch roll','oscilación','aircraft oscillating from side to side: our Yaw Damper system is inoperative and we are experiencing some Dutch roll','flight_ops'),
  ('duty time','tiempo de servicio','the time during which a crew is scheduled and authorised to work: The crew ran out of duty hours and a relief crew was needed.','flight_ops'),
  ('emergency exit','exit de salida','door or hatch fitted with an escape slide to allow the aircraft to be evacuated in 90 seconds in the event of an emergency: the passengers on USAir Flight 1549 used mainly the overwing emergency exits to evacuate the aircraft after the ditching','non_routine'),
  ('empennage','empenaje','the tail section of an aircraft, consisting of the fin, the tailplane and the part of the fuselage to which they are attached','aircraft'),
  ('en route','en ruta-en camino','on the way, in flight between two points: we are at FL 310 en route to Punta Arenas','navigation'),
  ('en-route charts','cartas de ruta','charts providing detailed information for IFR flight in upper airspace: navaids, tracks, navigational fixes, waypoints, sectors, standard airways, airport locations, minimum altitudes etc.','navigation'),
  ('encounter','encontrar','to meet, to experience: we encountered severe windshear from 500 feet to touchdown','weather'),
  ('endurance time','remanente- autonomia','an aircraft can fly without refuelling: we have 35 minutes (fuel) endurance','aircraft'),
  ('engine run-up','prueba de motor-turbina','operating the engine on the ground over its full power range for testing purposes after an engine change or repair','aircraft'),
  ('engine run-up area','área depruebas','pad or remote location where aircraft engines can be tested','aircraft'),
  ('engine stall','perdida de motor','margin the difference between the gas turbine operating line and the stall line','aircraft'),
  ('engineering','ingenieria','the technical department, responsible for aircraft maintenance: we will need to call Engineering to inspect our rear fuselage after a tail strike at take-off','aircraft'),
  ('enplane','abordar','to go on board the aircraft; to board','flight_ops'),
  ('enunciation','pronunciado','clear pronunciation of sounds to maximise understanding: a simple way to improve enunciation is to exaggerate normal mouth movements','airport'),
  ('erroneously','erroneamente','by mistake, by error: ‘1023’ was entered erroneously instead of ‘1013’ when the altimeter was set','weather'),
  ('escape slide','toboggan de escape','a rapid-inflation pneumatic channel to enable passengers and crew to evacuate quickly also referred to as a chute: inflatable escape slides can also be used as life rafts in case of ditching','non_routine'),
  ('evacuation','evacuación','exiting the aircraft in an emergency, often via the emergency escape slides','non_routine'),
  ('evaluate','evaluar','to judge, to assess, to analyse, to decide about: in the event of a system failure or structural damage the flight crew must evaluate the situation before making a decision.','flight_ops'),
  ('exceed','exceeder','to go beyond or over, to go too far: the crew have exceeded their legal duty time; you must not exceed 250 knots below 10,000 feet in this area','flight_ops'),
  ('expedite','acelerar-pronto','to perform as quickly as possible: we have a pressurization problem and need to expedite our descent','flight_ops'),
  ('extend the RAT','extender-sacar','to deploy the Ram Air Turbine, a small electrical generator driven by a propeller, which is lowered into the airstream below the wing to provide essential electrical (and hydraulic) power in the event of multiple engine-driven generator failures','aircraft'),
  ('extinguish','extinguir','to stop or put out a fire: we have managed to extinguish the fire and have the situation under control','non_routine'),
  ('fighter','avión de combate','military combat aircraft: The fighters flew alongside the cockpit to check that it was not a terrorist hijacking','security'),
  ('far end','final de pista','The end of a runway at the opposite end from where the aircraft touches down or starts its take-off run. Be advised there is debris at the far end of runway 27R','airport'),
  ('fit','ataque','An acute attack – can be epileptic or stroke or a fit of anger The passenger suffers from fits, periodically. Él periódicamente sufre de ataques','health'),
  ('fire engine','camión de bomberos','vehicle for spraying an extinguishing agent or water: request a fire engine standing by in case our brakes need cooling','non_routine'),
  ('flameout','perdida de potencia','flameout a loss of combustion in a gas turbine engine: The engine ingested a bird and had a flameout','non_routine'),
  ('flap asymmetry','asimetría de los flaps','when the flaps are not extended the same amount on both wings: A B737 flap asymmetry occurred on final approach to a short runway. The Captain requested vectors to a nearby airport with a longer runway','airport'),
  ('flaps-up landing','aterrizaje largo sin flaps','occurs when the crew is not able to extend the high-lift flaps. This results in the minimum speed of the aircraft being higher and so the aircraft landing at a higher speed and probably requiring a longer stopping distance','aircraft'),
  ('flare','subir la nariz - Rotar','the final nose-up pitch movement of a landing airplane. The landing flare is a maneuver that enables a pilot to reduce an airplane’s vertical speed without applying engine power.','aircraft'),
  ('flight crew','tripulación de vuelo','captain, first officer, and occasionally flight engineer working as a team','aircraft'),
  ('flight deck','cabina de vuelo','compartment from which the crew fly the aircraft; cockpit, flight compartment, control cabin','aircraft'),
  ('flight idle','potencia reducida','lowest engine power setting and r.p.m at which the engine can safely operate in flight: the engine should go from flight idle to take-off power in 6 seconds for a missed approach','aircraft'),
  ('flightpath / flighpath trajectory','cenda de planeo','of the aircraft in the vertical and horizontal planes: the aircraft’s flightpath can be reconstituted from DFDR data','flight_ops'),
  ('flight plan','plan de vuelo','specified information relating to the whole or portion of an intended flight: we filed our flight plan at 06:38; we wish to amend our flight plan','flight_ops'),
  ('flock','bandada','group of birds: a flock of seagulls has been reported near the threshold of Runway 19L.','airport'),
  ('flow','flujo','the movement of one flight after another, the number of aircraft passing through a given airspace','flight_ops'),
  ('foam carpet','espuma','a layer of foam put down on the runway by fire tenders to cushion the impact of an aircraft making a wheels-up landing. The fire services will put a layer of foam on the runway as the aircraft landing has no gear and they need to prevent fire','non_routine'),
  ('focus','concentrarse','to pay attention or concentrate on a particular point, subject or situation: the crew of Eastern Airlines Flight 401 were all too focused on fixing the landing gear indicator bulb and failed to notice that their aircraft was descending into the Everglades','aircraft'),
  ('foreign object','objeto extraño','the general name for something which should not be there: a bird, a plastic bag, metal debris etc. are all foreign objects which can damage the aircraft','flight_ops'),
  ('foreground','primer plano - fondo','the part of a scene situated towards the front or nearest to the viewer: In the foreground you can the baggage loading vehicles, in the background you can see the aircraft','flight_ops'),
  ('follow-me car','sigame','a car used to guide taxiing aircraft','flight_ops'),
  ('freighter','avión de carga','a plane for carrying heavy freight, such as industrial equipment, raw materials, livestock, food, parcels and goods','flight_ops'),
  ('frisk -','cachear','A body search of a passenger as a security check for illegal weapons-drugs The passengers were moved to one side and frisked by security - pronounced friskt','security'),
  ('galley','cocina','the part of the plane where the cabin attendants store and prepare food and drinks','aircraft'),
  ('gantry','maquina descongelante','a metal framework shaped like a bridge used for de-icing at the airport','weather'),
  ('garbled','confuse- ilejible','unclear, inaudible, typically because of technical problems: say again, your last transmission was garbled','flight_ops'),
  ('gate','puerta-pasarella','parking stand directly connected to the airport terminal by an airbridge: we are pushing back from Gate 36; will you have an ambulance standing by at the gate?','airport'),
  ('gear','tren','the landing gear, i.e. the wheels and the mechanisms connected to them: V2 … positive rate …. Gear up ; the gear is retracted','aircraft'),
  ('give way','darle paso','to let another aircraft pass first during ground movements: give way to the 787 passing from right to left','flight_ops'),
  ('glare','reflejo','bright reflected or refracted light','flight_ops'),
  ('glareshield','filtro','cockpit panel above the main instrument panels and below the windshield which protects the instruments from reflection and on which the automatic flight control panel is located','aircraft'),
  ('go ahead','prosiga','This can mean 1) move forward, or 2) do what you intended to do. It is a dangerously ambiguous phrase and should be avoided in aviation communication. OACI now uses “pass your message”','navigation'),
  ('grab','agarrar','to seize, to get hold of: grab the handle and pull it down','flight_ops'),
  ('ground handler','persona que pone los tacos','airport agent who usually installs and removes wheel chocks and supervises the push-back of the aircraft with a tractor / tow vehicle / tug','airport'),
  ('gusty','rafagas','gusty conditions are when the wind speed changes suddenly: wind is gusting 15 to 20 knots','weather'),
  ('hail','granizo','precipitation in the form of compacted ice and snow: hail storms can cause significant structural damage','weather'),
  ('handle','manejar una situación','to deal with or to manage a situation: flight crew are trained to handle unexpected and abnormal situations','flight_ops'),
  ('handoff','cambio de control de área','a transfer of a flight from one controller or area to another: also handover','navigation'),
  ('handover','transferencia de controles','a transfer of a flight from one controller or area to another; also a verb, to hand over (v). See also handoff.','navigation'),
  ('hazardous','peligroso','dangerous, representing a threat, a danger or a risk: the ramp area is hazardous during turnaround and staff wear high-visibility vests','security'),
  ('haze HZ','neblina','fine dust or vapour causing an unclear, clouded atmosphere','weather'),
  ('heads-down','mirando los instrumentos','of a crew member who is focused on the flight instruments rather than looking outside the aircraft','aircraft'),
  ('headwind','viento de frente','a wind blowing in a direction opposite to the direction of travel of the aircraft. Its opposite is tailwind.','weather'),
  ('hijacker','secuestrador','terrorist who tries to take control of an aircraft and its crew in order to obtain demands, make a political statement using threats, or to deliberately crash the plane: the transponder code 7500 is used in the event of a hijacker on board','security'),
  ('humming','sonido suave','a low buzzing noise, to make a low continuous vibrating sound: there was a humming sound in the background and I couldn´t hear the transmission','flight_ops'),
  ('hurt','dolor','to injure, to harm, to cause pain: one of the passengers was hurt when he fell on the icy steps and cut his leg','health'),
  ('hypoxia','falta de oxigeno','a deficiency of available oxygen in the blood and bodily tissue, an inadequate amount of oxygen being supplied to the brain, for example at high altitude in the event of cabin depressurization. In the case of rapid decompression at 40,000 feet the resulting hypoxia will mean that the time of useful consciousness will be about 20 seconds; it is therefore essential to don oxygen masks and initiate an emergency descent immediately.','health'),
  ('idle','posición en minimos','the minimum smooth engine operating speed: flight idle, ground idle','aircraft'),
  ('idling','minimos del motor en tierra','operating an engine at its minimum smooth rotating speed','aircraft'),
  ('inadequate','inadecuado','not good enough, not of a sufficient quantity: there was inadequate warning of the trench being dug along the side of the taxiway','airport'),
  ('inadvertently','sin intención','unintentionally, without being aware: the crew inadvertently strayed onto the active runway','airport'),
  ('inebriated','ebrio, embriagado','to make drunk; intoxicate. The passenger was totally inebriated, having taken a mixture of drugs and alcohol. .','security'),
  ('inbound','tramo de acercamiento','used to describe an aircraft which is flying towards a point, towards a fix, arriving, approaching: we are flying inbound heading 22; track inbound to the Norfolk VOR on the 193° radial.','navigation'),
  ('induce','inducir','to cause something to happen: the crew’s familiarity with this approach induced a sense of complacency','flight_ops'),
  ('ingest','ingestar','to suck or pull into, to swallow, to suck a bird into the engine: Canada geese were ingested into both engines at 3,000 feet, causing a dual engine loss on USAir Flight 1549','aircraft'),
  ('injury','hacer daño','hurt done to a person’s body: cuts, bruises, fractures, concussion, bleeding are all forms of injury','health'),
  ('inoperative','inoperativo','a general term meaning that a system or part cannot operate correctly, also inop, unserviceable','flight_ops'),
  ('instinctive disconnect push button','botón de desconexión del piloto automático','small red pushbutton on the control wheel or side stick used to disconnect the autopilot quickly','flight_ops'),
  ('intermittent','intermitente','of a phenomenon which appears and disappears: we have had intermittent signal loss, but it seems to be operating normally now','flight_ops'),
  ('interpretation','interpretar','a way of understanding something: people’s interpretation of different cultural behaviour varies','airport'),
  ('intersection','intercección','crossing of taxiways, runways or taxiways and runways','airport'),
  ('intoxicated','intoxicado con droga o alcohol','under the effects of drugs or alcohol, drunk: there is a very intoxicated and belligerent passenger in the rear','security'),
  ('isolate','aislar','to shut off the electrical, hydraulic, fuel or pneumatic supply to a failed component: we have isolated the leak','non_routine'),
  ('item','punto','a point, a piece of information or an action: the checklist consists of six items','flight_ops'),
  ('jammed','bloqueado','blocked in position, especially used about the flaps, slats and servocontrols: the trailing edge flaps seem to be jammed in the 15-degree position','aircraft'),
  ('jettison','soltar-descargar','to discharge fuel in flight in order to reduce the aircraft’s weight; to dump','aircraft'),
  ('jetway','Puente','a telescopic walkway for passengers disembark from and board the aircraft directly to and from the terminal building; also airbridge or jetty','airport'),
  ('key in','entrar-programar','to enter data into a computer system using a keyboard: Key in the coordinates of our alternate. Key in the data to the FMS','flight_ops'),
  ('leading edge','borde de ataque','the forward part of the wing, engine blades or stabilizers: the leading edge slats are extended','aircraft'),
  ('leakage','gotear','unintentional flow of fluid from a container or system which can be measured in drops per minute: We appear to have a fuel leakage from the inner left hand tank','non_routine'),
  ('leg','tramo','part of a long-haul journey, where the plane stops to refuel one or more times on the way: The first leg of the journey is from Beijing to Anchorage; we then fly on to Washington. a phase of a circuit or traffic pattern: departure, crosswind, downwind and base legs','weather'),
  ('length','longitud','the linear extent or measurement of something from end to end, usually being the longest dimension: We have no brakes - What is the length of the runway?','airport'),
  ('load shed','reducir','the disconnection of non-essential electrical power users (notably the galley) if there are electrical generation failures in order to give priority to the essential systems. We need to shed some load on the power bus to divert power to…','flight_ops'),
  ('load master','persona a cargo del equipaje','person in charge of a team of handlers loading and unloading cargo and baggage. Baggage loading devices are one of the main causes of damage to the aircraft during turnaround','flight_ops'),
  ('long haul','ruta larga','long distance or long range: 4-engine and ETOPS aircraft are operated on long haul flights','aircraft'),
  ('loose','suelto','not correctly attached or secured, detached, unfastened: there are loose pieces of plastic blowing around the apron - one of the pallets is loose. Note the opposite of loose is tight or locked. The engine cowling looked loose and needs tightening','airport'),
  ('loss','perder','when you do not have something you had before, because it is unavailable, not working, or destroyed: We experienced a loss of power; the fire resulted in a complete hull loss.','non_routine'),
  ('low ceiling','techo bajo','the height of the first of cloud cover at a short distance from the ground','weather'),
  ('low pass','pasar bajo','a flight at low altitude in landing configuration above the aerodrome usually so that the Tower controllers can check whether the landing gear seems correctly extended and locked down. Landing Gear does not appear to have extended. Request Low Pass for visual inspection','navigation'),
  ('lower cargo deck','compartimiento de carga','space below the cabin floor which is divided into a forward and aft cargo hold and which on larger aircraft may be subdivided into compartments. The holds / compartments are subdivided into bays each one of which corresponds to the size of a ULD or container.','aircraft'),
  ('manoeuvrability','maniobrabilidad','refers to the extent to which an aircraft can manoeuvre, i.e. move around, get into the right position: manoeuvrability may be reduced if there are flight control problems','flight_ops'),
  ('marking','marcas','indication painted horizontally onto the runway or taxiway: holding points are identified by continuous and broken yellow markings','airport'),
  ('marshaller','señalero','a person in charge of guiding the aircraft to its stand using hand signals: marshallers often use bats or lighted batons to give signals','airport'),
  ('meal tray','bandeja de comir','flat support containing food: catering delivered 139 standard and 21 vegetarian meal trays','airport'),
  ('medium haul','trayectos medios','medium range flight: medium haul flights usually last from between three to five hours','flight_ops'),
  ('metal debris','pedazo de metal','parts which may become detached from aircraft during take-off and landing; they can have devastating effects as was shown by the Air France Concorde accident at Charles de Gaulle','flight_ops'),
  ('mild','blando','Not strong. Weather conditions today are quite mild','flight_ops'),
  ('miss','perder','a near-collision, an airprox: It was a near miss, as separation was reduced to 650 feet vertically and 1,200 metres horizontally. You can also “miss” your flight if you are stuck in traffic','flight_ops'),
  ('misunderstanding','no entendi','understanding incorrectly: there was a misunderstanding between the pilot and the controller and the crew continued their descent.','navigation'),
  ('mitigate','mitigar','to make less serious: the crew made a long approach to mitigate the risk of landing long','airport'),
  ('molten fused or melted','derretir','molten plastic and metal were found at the scene of the fire.','non_routine'),
  ('monitor','monitorear','to listen to the frequency: The captain monitored the approach frequency whilst the co-pilot conducted the pre-landing checks to watch indications over time: monitor the Engine 2 parameters','navigation'),
  ('mud','barro-lodo','soft wet earth: A runway excursion can often mean that the nose gear gets bogged down in the mud','airport'),
  ('no-entry sign','señal de no entrar','airport sign which indicates that a taxiway etc. is closed or unserviceable. A no-entry sign is a white rectangle on a red circular background.','airport'),
  ('noise','ruido','unwanted signals within an electronic system: We’re getting a lot of noise on the tower frequency sound: What was that noise from the cabin?','navigation'),
  ('notify','notificar','to inform, to advise, to tell: Notify all incoming flights of the recent reports of windshear near the threshold','weather'),
  ('occur','ocurrir','to happen, to take place: a bird strike occurred during climb-out','flight_ops'),
  ('odour','olor','Smell, often unpleasant; there was an unpleasant odour coming from the aft of the cabin.','aircraft'),
  ('offload','descargar','to remove from the aircraft: as the passenger did not show up at the gate, his baggage had to be identified and offloaded','airport'),
  ('offset','fuera del track','to shift or displace to the side of a central axis: crews cannot offset their flight paths in RVSM conditions if parallel route centrelines are less than 30 nm apart','flight_ops'),
  ('omit','omitir','to fail or forget to do something: the controller omitted to use the complete call sign','navigation'),
  ('on board','a bordo','on the aircraft: we have 358 passengers on board (POB)','flight_ops'),
  ('onward clearance','prevea','a clearance to pursue the flight after a waypoint or holding action: expect onward clearance at 09','navigation'),
  ('orbit','órbita','to perform a 360° circuit usually in order to delay: for safety reasons, the ATC will tell the pilot whether to orbit left or right.','navigation'),
  ('outer windshield panel','vidrio exterior del parabrisas','external layer of a windshield; aircraft windshields comprise up to five separate layers, incorporate gold heating filaments and may weigh up to 80kg.','aircraft'),
  ('outlying stand','plataforma','parking position which is not directly connected to terminal; remote stand','airport'),
  ('outlet','toma de corriente','a point in a wiring system from which current can be taken to supply electrical devices. There is a power outlet next to your seat to which you can plug in your laptop','flight_ops'),
  ('overcast OVC','cubierto','complete cloud cover, 0.9+ (i.e. over 90%) cloud cover. The sky is quite overcast today; RVR is reduced to 3 miles','weather'),
  ('overfly','sobrevuelo','to fly over: aircraft overfly waypoints and beacons','navigation'),
  ('overflow','derramarse','to fill or be filled beyond capacity so as to spill or run over: the fuel was filled beyond the tank capacity and overflowed from the tank','aircraft'),
  ('overhead','sobre','immediately above: we are overhead the field','flight_ops'),
  ('overhead panel','panel encima de los pilotos','an instrument panel above the pilots’ heads in the cockpit which contains most of the system control panels on aircraft with a two-man crew','aircraft'),
  ('overheat','recalantarse','Become too hot: The rear toilet fan had overheated; the brakes had overheated and needed cooling down by the fire brigade','non_routine'),
  ('overloaded','sobrecarga','Electrical power surge: the rear toilet circuit breaker had overloaded due to the fan overheating','flight_ops'),
  ('over-reliance','dependiente','depending on somebody or something too much, which creates dangers when that person or thing is unavailable or wrong','flight_ops'),
  ('override','pasar a modo manual','to give a manual order which has priority over an automatic order: the crew can always override the automation manually and take control','flight_ops'),
  ('overshoot','pasarse de..','to fail to stop before the runway exit or the runway threshold. The plane overshot the runway and made an excursion','airport'),
  ('overtake','adelantar','Pass another plane. SB 23 you need to overtake the 737 stopped on taxiway Mike','airport'),
  ('pallet','pala para carga','flat wooden trays transporting goods','flight_ops'),
  ('paperwork','trabajo administrativo','filling in forms, records, documents, reports etc.','flight_ops'),
  ('parking brake','freno de parqueo','wheel brake applied from the flight deck by means of a handle and used on the ground at the stand until the chocks are in place or for emergency braking as a last resort','airport'),
  ('pass','reporter pasando','to go through or by: report passing PAR / Flight Level 160','navigation'),
  ('pass through','a través','to cross, to move from one side to the other: we are passing through some dense cloud','flight_ops'),
  ('pass your message','prosiga','to transmit or give your message. ICAO requires use of “Pass your Message” instead of the ambiguous “Go Ahead”','navigation'),
  ('passenger address PA','microfono a los pasajeros','a communication system for the flight and cabin crew to talk to all the passengers or the communication itself','aircraft'),
  ('passenger coach','bus para pasajeros','bus for transporting passengers to and from aircraft','flight_ops'),
  ('passenger steps','escaleras','mobile stairs used for boarding and disembarking at outlying stands: We shall require passenger steps as the airbridge is inop','airport'),
  ('paving','pavimento','the hard surface of all parts of the apron, runways and taxiways','airport'),
  ('pax','pasajero','a common abbreviation for passengers: We have 164 pax on board','flight_ops'),
  ('payload','carga','carrying capacity of an aircraft ( cargo, Pax, Crew, Fuel, baggage). The dispatcher advised the need to uplift more fuel as the PAX payload was heavy the part of the useful load from which revenue is derived','aircraft'),
  ('penalty','penalizar','a reduction in aircraft or system performance caused by a failure: we have a 20-knot speed penalty due to the engine malfunction','aircraft'),
  ('perform','ejecute -realize','to do, to carry out, to execute a procedure: we will perform a missed approach','flight_ops'),
  ('perimeter fencing','perimetro','security barrier around the outer limit of airport','airport'),
  ('perishable goods','comida perecedera','items such as fresh food which must be kept under specific conditions to protect them from spoiling too soon','flight_ops'),
  ('pick up','escucho','to detect something heard on the frequency; the LAN Chile crew picked up the PAN PAN call from the TAROM flight and relayed it to ATC','non_routine'),
  ('port','babor','Left: The port engine has been hit by a bird and has flamed out','non_routine'),
  ('plug in','conectar - enchufe','a device that can be connected by means of a plug. The headset will not work unless it is plugged in correctly; Make sure your computer power cable is plugged in','flight_ops'),
  ('precautionary landing','aterrize con precaución','an anticipated landing decided on by the crew in order to manage an abnormal situation (technical failure, illness etc.) but which is not an emergency: due to the failure of engine 1, we have decided to return to Bogota and make a precautionary landing','aircraft'),
  ('precipitation','precipitación','moisture released from the atmosphere and falling as rain, snow, hail etc.','weather'),
  ('pull in','hacerse a un lado de la pista','to move to the side of the road / taxiway, etc., to allow another vehicle to pass; also pull over','airport'),
  ('push-back','remolque atras','moving the aircraft back away from its parking stand so that the crew can start the engines and taxi: request push-back – push-back approved','airport'),
  ('pylon','pilon','a structure used to mount engines to the underside of an aircraft wing a tall steel structure to which wires carrying electricity are fixed so that they are safely held high above the ground: there is a row of pylons rising to 150 feet on final approach to the left of the centerline','aircraft'),
  ('puzzled','desconcertado','confused. The Co Pilot was puzzled by the instruments parameters','aircraft'),
  ('quiet hours','horas tranquilas','the time, typically 23:00–06:00, when aircraft movements to and from the airport are restricted or prohibited to avoid disturbance by noise: we need to expedite our departure or we will be into quiet hours on arrival','airport'),
  ('ramp','rampa','area around the terminal buildings where aircraft are parked and serviced. Also apron.','airport'),
  ('ramp supervisor','supervisor de rampa','person in charge of a team of handlers loading and unloading cargo and baggage in case of any special cargo. Baggage loading devices are one of the main causes of damage to the aircraft duringturnaround. Radome – nose cover for doppler and weather Radar reach (alcanzar) to arrive at a given point: the aircraft levelled off on reaching its top of climb','airport'),
  ('read','copia','to hear and understand: how do you read me?','airport'),
  ('read back','colaciónar','an instruction to make the interlocutor acknowledge specific instructions or information: The readback was both incomplete and given with the wrong stop altitude; the ATCO had corrected the omission but missed the stop altitude error','navigation'),
  ('read back error','error de colación','a failure to correctly repeat all or part of message to verify accuracy','navigation'),
  ('readout','lectura','data which is displayed visually: the FOB (Fuel On Board) readout is showing 38 tonnes data said / played audibly: the PNF made a radio altitude readout during approach','navigation'),
  ('ready','listo','prepared. Are you ready to push-back?','flight_ops'),
  ('reboot','reinicializar','to shut down and restart (a computer system) or (of a computer system) to shut down and restart. If the computer systems fails, try to reboot it.','flight_ops'),
  ('reclear','modificar la autorización','to modify a previous ATC clearance: recleared Flight Level 310; rest of clearance unchanged','navigation'),
  ('recovery','recobrando','the completion of a flight manoeuvre and return to straight and level flight: The pilot disengaged the auto-pilot and recovered control of the aircraft. the return to normal operation, for example the restarting of engine of the regaining of a previously lost system: the APU recovered when the Engine restarted','aircraft'),
  ('recycle','reciclar','to perform a complete flight control, landing gear or door operation: extend-retract-extend, close-open close etc. The First Officer recycled the landing gear for landing','aircraft'),
  ('refraction','refracción','the deflection of a light ray from a straight path, which causes visual distortion','flight_ops'),
  ('reject','abortar','to refuse, to abandon: the crew rejected take-off at 70 knots','flight_ops'),
  ('relay','retransmitir','to pass on or transmit information: Will you relay our situation to our company Ops, please?','flight_ops'),
  ('relief crew','tripulación de relevo','a flight crew on the ground or on board who replaces a crew at the end of their period of duty','flight_ops'),
  ('relieve','aliviar','to remove pressure, strain or pain: Good ground support during turnaround can relieve pressure on flight crews. to take over from someone: Regulations state that controllers must be relieved after an eight-hour shift and that there must be at least ten hours between shifts.','navigation'),
  ('relight','encender','to restart an engine (past: relit), We are trying to relight our stalled engine','aircraft'),
  ('reluctance','indisposición, duda, falta de voluntad','a lack of willingness, often because of fear of embarrassment or simply to save time and effort: The First Officer showed a lot of reluctance to question the Captain’s decision','flight_ops'),
  ('remote stand','puerta remota','parking position which is not directly connected to the terminal; outlying stand','airport'),
  ('repair station','estación de reparación','a technical facility where certain types of aircraft, engines and equipment can be repaired and maintained','aircraft'),
  ('reset','reiniciar','Button to reset-restart system. When the circuit breaker trips, reset it.','flight_ops'),
  ('resume','reanudo','to start using or doing again, to return to again after an interruption: resume own navigation direct CALI','flight_ops'),
  ('resuscitation','resucitar','bringing someone back to consciousness. The flight attendant was able to resuscitate the passenger after his heart attack.','health'),
  ('retard','cortar potencia o reducer al minimo','to pull back the throttle / thrust lever(s) on the centre pedestal to reduce the engine speed','aircraft'),
  ('to throttle back','retard','just prior to touchdown the automatic system in the flight deck says ‘retard, retard’.','flight_ops'),
  ('retract the gear','subir tren','to set the landing gear lever on the right centre part of the instrument panel to UP; the landing gear is unlocked, folds and enters the landing gear bays: the landing gear bay doors open to allow the landing gear to retract. Other words used – WindUp, Recycle','aircraft'),
  ('reverse thrust','potencia reversa','engine thrust whose direction is changed during the landing roll-out by a translating cowl, doors or buckets in order to reduce aircraft speed and assist the wheel braking','aircraft'),
  ('revert','revertir','to return to: revert to flight plan call sign','flight_ops'),
  ('ride','vuelo','jargon for flight: we are having a smooth ride','flight_ops'),
  ('ridge','cresta de la montaña','Peak, Top of hill, mountain terrain. There is a ridge of hills rising to 1850 metres height, east of the field','flight_ops'),
  ('ridge of high pressure','sistema de alta presión','weather forecast: elongated area of high atmospheric pressure There is a ridge of high pressure over the country, so we should have good weather for the next few days. Se aproxima un frente de alta presión que vendrá acompañado de un descenso de la temperatura.','airport'),
  ('rim','rin,llanta','the outer lip of a wheel, which holds the tyre in place','aircraft'),
  ('risk factor','factor de riesgo','an aspect which can be a source of danger or threat: Poor visibility, crew fatigue, failure to follow SOPs are all potential risk factors during approach and landing','security'),
  ('roll through','a travez de','to taxi past, to fail to stop at: the crew inadvertently rolled through the stop bar','airport'),
  ('rough','agreste','Weather – Stormy Expect Rough weather at 50 nms ahead','flight_ops'),
  ('rough approximation','idea aproximada – estimación','Something close but not exact. It is roughly 100 nms to your Alternate','flight_ops'),
  ('rough Surface','superficie rugosa','Uneven or bumpy texture. Runway 25L has a rough surface due to the bad storms','weather'),
  ('run away','se subio','to increase in an uncontrolled manner: The temperature indications seem to be running away.','flight_ops'),
  ('runway incursion','incursion en pista','when an aircraft, vehicle, pedestrian or animal inadvertently enters an active runway','airport'),
  ('rupture','romper-ruptura','a break or failure. The hydraulic hose ruptured spilling fluid on the Apron.','non_routine'),
  ('rushed','apuro','in a hurry, in haste, too fast to do things properly: rushed decisions and actions often lead to errors and inattention','flight_ops'),
  ('saturated','saturado','Too much “traffic”: the frequency was saturated with too much traffic','navigation'),
  ('safety','seguridad','the protection of people from harm, injury, danger and death: safety audit, safety management system, passenger safety: Aviation safety is the reason behind ICAO’s Language Proficiency Requirements.','health'),
  ('scheduled','horario','planned at a specific time, regular: Both scheduled and charter flights use the airport.','airport'),
  ('scissor lift','rampa o tijera que sube la carga al avión','loader telescopic loader for raising containers and pallets to the cargo compartments','flight_ops'),
  ('scratch','rayon','a shallow line or incision in the surface of a material; The catering truck slightly scratched the plane’s fuselage','aircraft'),
  ('seepage','goteo lento o filtración','a very slow fluid leak, fluid was seeping from the hydraulic hose','non_routine'),
  ('seize','bloquear, agarrar','to block, lock or jam: the flap linkage appears to be seized up to grab or take hold of: seize the handle and turn clockwise','aircraft'),
  ('setup','preparación','preparation, calibration, selection severely (severamente) opposite is “slightly” badly, considerably, seriously: the lower wing surface was severely damaged by the burst tyre','aircraft'),
  ('setting','nivel – ajuste','value entered,calibration, position of flight control surface, engine, system or instrument: the altimeter setting is 1007 hPa; reduce the engine power setting The setting on the thermostat was too cold, so she changed it. El nivel del termostato estaba muy bajo, así que lo cambió.','navigation'),
  ('shed','desconectar','to disconnect certain heavy non-essential electrical loads such as the galley','flight_ops'),
  ('shift','cambiar','handover the moment one group of controllers is replaced by another or one control centre passes control to another','navigation'),
  ('short circuit','corto circuito','an inadvertent electrical connection which can cause an electrical failure, a circuit breaker to open or an electrical fire. The electrical fault cause the circuit breaker to trip','non_routine'),
  ('shrouded','envuelto','a cover of fog or mist The airport was shrouded in fog','weather'),
  ('shutdown','apagar','reducing engine or APU power to zero, stopping engine operation SID Standard Instrument Departure, a pre-planned, coded ATC IFR departure routing','navigation'),
  ('sign','señal','an indication mounted vertically on a signpost and illuminated at night','flight_ops'),
  ('sill -door','umbral','the lower horizontal part of the aircraft door frame','flight_ops'),
  ('skid','derrapar','to slide sideways, sometimes out of control after sudden braking. The aircraft skidded out of control off the runway (excursion)','airport'),
  ('skin','revestimiento','the fuselage, wing and empennage panels which make up the outer airframe of the aircraft','aircraft'),
  ('slide','tobbogan','a rapid-inflation pneumatic channel to enable passengers and crew to evacuate quickly; also referred to as a chute: one of the slides failed to deploy','non_routine'),
  ('slightly','pequeño','a little, a small amount: the door is only slightly damaged','flight_ops'),
  ('slippery','resbaloso','which is likely to cause sliding or skidding: the runway is slippery when wet','airport'),
  ('slope','cenda','a gradient, angle to the horizontal: the aircraft is descending on a 3-degree slope','flight_ops'),
  ('smoke','humo','fumes caused by combustion. Both smoke and fire remain number one hazards on board the aircraft. Response time is critical. The crew’s priority is to land as soon as possible while trying to contain and extinguish the fire. The flight crew will be working under a lot of stress. Communication will be less clear as they crew will be wearing masks. It will be necessary to make an emergency evacuation using the escape slides as soon as the aircraft is on the ground.','non_routine'),
  ('snow blower','carro que limpia la nieve','vehicle which clears runways of snow by blowing','airport'),
  ('snow plough','carro que limpia la nieve','vehicle which removes snow from runways with a large blade','airport'),
  ('spacing','espaciamiento','a safe distance between aircraft. A key role of an ATCO is to maintain spacing at all times. See also separation. starboard (estribor) Right GREEN:','flight_ops'),
  ('spurious','advertencia','referring to an indication, message or warning, not based on true facts, and which may in fact be the result of a problem with the warning system','flight_ops'),
  ('stack','compilacion de aviones','a superimposed series of holding patterns at assigned flight levels','navigation'),
  ('stand','puerta de parqueo','the place where the aircraft parks, where passengers board and disembark.','airport'),
  ('sterile cockpit','cabina esteril','cockpit environment in which there are no audio or visual distractions from the piloting tasks: a sterile cockpit is one of the prerequisites of a safe working environment','aircraft'),
  ('stick shaker','alarma de perdida - vibración','an aircraft stall warning system which when triggered by the angle of attack sensor causes the stick or control column to vibrate so that the pilot gives a nose-down order','flight_ops'),
  ('sticking mike','microfono se bloquea','a microphone which is blocked in the open position','flight_ops'),
  ('stop bar','luces indicadoras de parada','a series of lights indicating whether access to a runway is authorised or not: do not proceed if the stop bar lights are red','airport'),
  ('stopway','pista adiciónal','additional paved area beyond the normal end of the runway to allow for aircraft overrunning in an emergency','airport'),
  ('stow','guardar','To pack or out away. Passenger carryon baggage can be stowed in the overhead locker. There is a life jacket stowed under your seat','flight_ops'),
  ('stray','entrar por error- perderce','to enter an area or airspace by mistake: the pilot was distracted and strayed onto the active runway','weather'),
  ('strength','aumenta el volume','force, volume or loudness of a radio transmission: signal strength varied during the storms','flight_ops'),
  ('stretcher','camilla','a collapsible canvas bed for carrying an injured person: we will need a stretcher to carry off the injured passenger','health'),
  ('strip','pequeña','a piece of paper or cardboard, or an electronic equivalent, which enables a controller to record basic data about a flight and manage flow control.','navigation'),
  ('stuck','no se puede mover','blocked in one position, unable to move: the microphone selector is stuck','flight_ops'),
  ('suitable','apropiado','appropriate, convenient: we need to divert to a suitable alternate','flight_ops'),
  ('sudden','rapido - de repente','unexpected, rapid: there has been a sudden change in wind velocity','flight_ops'),
  ('surge','sobretension','a sudden irregular flow of fluid, especially in the engine, electrical or hydraulic system, which causes a malfunction; in the case of an engine, this results in an engine stall: the electrical surge caused the circuit breakers to trip','aircraft'),
  ('sweep','barrer','to move over a wide area in a large arc: the weather radar antenna sweeps an area of +/- 45 degrees ahead of the aircraft; the windshield wipers sweep the windshield clear of rain','aircraft'),
  ('sweeper vehicle','carro barredor','with rotary brush for removing dirt and debris','flight_ops'),
  ('switch','cambiar','to transfer, to move from one position or selection to another: Can you switch to the Tower frequency?','navigation'),
  ('take over','reemplazar','to replace someone in the function they are performing: the next shift will take over at 18:00.','flight_ops'),
  ('target','blanco','point which you aim at, which you wish to reach or hit: There is a white painted touchdown target on the runway; A target speed can be set on the speed scale a radar echo displayed on the screen','airport'),
  ('terrain','terreno','Ground type. Caution – Be Advised -There is mountainous terrain rising to 1850 metres to the East of the field on approach','flight_ops'),
  ('thoroughly','meticuloso','completely, rigorously, methodically. Make sure you thoroughly check the weight and balance print out before you it sign-off','flight_ops'),
  ('threat','riesgo, amenaza','a suggestion that something unpleasant or violent will happen: there is a threat of airport closures caused by the strike; the threat of tropical storms a danger: Bird strikes remain a serious threat to aircraft safety','security'),
  ('threaten','dar señales de peligro','to give signs or warnings of harm or danger: Windshear can threaten the stability of aircraft on final approach to force someone to act under duress: the terrorist is threatening the crew','weather'),
  ('threshold','umbral','the beginning of the runway: There is debris at the threshold of runway 27R','airport'),
  ('throttle back','reducir','to pull back the throttle / thrust lever(s) on the centre pedestal to reduce the engine speed and the resulting thrust; to retard','aircraft'),
  ('throttles','aceleradores','levers on the centre pedestal which control engine thrust','aircraft'),
  ('thrust','potencia','the propulsive force generated by an aircraft engine; the other three forces which act on an aircraft are lift, weight and drag','aircraft'),
  ('thud','sonido-golpe fuerte','a deep, dull noise caused by an impact: the cabin crew heard a thud shortly before lift-off; we are wondering whether a tyre had burst','aircraft'),
  ('tripped','deactivar','When a circuit breaker trips, it is deactivated. The circuit breaker has just tripped – Check the panel','flight_ops'),
  ('tight circuit','circuito cerrado','a traffic pattern turn with a short radius','flight_ops'),
  ('timely','apropiada','at the right time: the controller made a timely decision and instructed the aircraft to climb immediately','navigation'),
  ('torching','llamas del exosto','flames coming from the engine exhaust duct due to the presence of fuel which has not been burnt','non_routine'),
  ('tow vehicle','pay-mover – carro de remolque','a vehicle used especially during pushback to move an aircraft backwards from the stand or to pull it to another location at the airport. It is also referred to as a tug or tractor','airport'),
  ('tow-bar','gancho de remolque','connecting the aircraft nose gear to a tow vehicle for pushback and towing: The plane was delayed whilst as the wrong tow bar was connected','flight_ops'),
  ('tractor','tractor','a towing vehicle, used especially during pushback, i.e. moving a plane backwards from the stand. It is also referred to as a tug or tow vehicle','airport'),
  ('trailing edge','flaps','the rear edge of the wing, stabilisers and engine blades: trailing edge flaps','aircraft'),
  ('tread','toca/banda de rodadura','the thick moulded part of a plane tyre that grips the runway – on walk around inspection, the tire tread looked worn / bald The tire was de-treaded','airport'),
  ('trend -tendency','tendencia','general movement or direction in development: a trend forecast shall supersede, during the validity of the trend, the aerodrome forecast (TAF) for the aerodrome concerned','airport'),
  ('tug','carro de remolque','a towing vehicle, used especially during pushback. It is also referred to as a tractor or tow vehicle: We are waiting for the tug to arrive so that we can push back','aircraft'),
  ('turnaround','transito – tiempo de entrega','the time between the arrival of a flight at its parking stand and its departure for the next flight; it is a period when the flight crew’s attention is turned to a whole series of activities (servicing, unloading, loading, refuelling, catering, engineering, boarding etc.) where the airport ground staff is involved and contact with Air Traffic Control is limited. However, the flight crew also communicate with different categories of ground staff both by radio / interphone and face to face in situations where safety is an ongoing concern and the operational time constraints to depart on time create what is a potentially stressful environment.','weather'),
  ('unable','no possible','‘I cannot comply with your request, instruction or clearance’; ‘unable’ is usually followed by a reason. Having only one possible meaning. If a word or sentence is ambiguous (de una manera), it may be interpreted in several ways','navigation'),
  ('unaware','no realizo o inconsciente','not knowing, not realizing: The cockpit crew were unaware of the situation in the cabin','aircraft'),
  ('under control','bajo control','controlled, not out of hand: Following the engine flame-out, the captain announced that the situation was under control','non_routine'),
  ('unfamiliar','no estar familiarizado con','having little knowledge of, not being aware of; the co-pilot was unfamiliar with the airport taxiways','airport'),
  ('unruly','agresivo','aggressive, belligerent, badly behaved: we have a group of unruly football fans on board','security'),
  ('unserviceable','inservible','which cannot be used on the aircraft and must be replaced or repaired. Also U/S.','flight_ops'),
  ('updated','al día o actualizado','in the most recent version: make sure that the charts you use have been updated','flight_ops'),
  ('uplift','recargar','to take fuel on board the aircraft, to refuel: we need to uplift 69 tonnes of fuel','aircraft'),
  ('vacate','dejar vacante','Depart from ,exit from. Vacate Runway via Taxiway B1, Vacate Gate 23 expeditiously','airport'),
  ('via','vía','passing by or through: taxi to holding position via November and Lima','flight_ops'),
  ('vicinity','cercania','surroundings, neighbourhood: there is VFR traffic in the vicinity of the aerodrome','airport'),
  ('wake turbulence','estela turbulenta','a downdraught caused by the movement of a large aircraft through the air. For this reason, ATC usually provides additional horizontal separation after the passage of particularly large aircraft; also wake vortex','weather'),
  ('walk around inspection','inspección 360 - prevuelo','an external check of the aircraft made by the first officer at the stand between two flights; he makes sure that there is no apparent damage. The first officer noticed that the right hand navigation light cover was cracked on walk around inspection','airport'),
  ('warning','alarma de advertencia','a crew alert symbolised by the colour red and requiring immediate crew action. We have an engine fire warning','non_routine'),
  ('wear','gastado','damage from being used regularly, as in clothes, paint, mechanical parts etc. that gradually deteriorate as they get older: There is a lot of wear on the wingtips','flight_ops')
on conflict do nothing;
