-- ============================================================================
-- Convocatorias de piloto de las aerolíneas, leídas de sus portales de empleo.
--
-- La función de borde `revisar-convocatorias` (supabase/functions) lee Copa,
-- Avianca, JetSMART, Wingo y SATENA y deja aquí lo que encuentra; pg_cron la
-- llama cada 6 horas. La app lo lee para el aviso «Convocatoria abierta» y el
-- botón «Ver requisitos» de la portada y de Elegibilidad.
--
-- LATAM no se lee sola: el robots.txt de su portal prohíbe leer la lista de
-- vacantes. Se marca a mano con private.convocatoria_manual(), y aquí se deja
-- cargada su página de pilotos con los requisitos que publica.
--
-- Nada se borra: lo que deja de aparecer se marca `abierta = false` con su
-- fecha. La última convocatoria de cada aerolínea sirve aunque haya cerrado,
-- porque dice qué pidió.
-- ============================================================================

create extension if not exists pg_net with schema extensions;

create table public.convocatorias (
  id bigint generated by default as identity primary key,
  airline_id bigint not null references public.airlines (id),
  -- El id en la fuente (Copa: el de Oracle; Avianca y JetSMART: el de la URL).
  clave_externa text not null check (clave_externa ~ '^[A-Za-z0-9-]{1,80}$'),
  cargo text not null check (cargo in ('primer_oficial', 'cadete', 'piloto', 'capitan')),
  -- `vacante`: una convocatoria puntual. `pagina`: la página de pilotos de la
  -- aerolínea, que está siempre y dice si hay vacantes o no (Wingo, LATAM).
  tipo text not null default 'vacante' check (tipo in ('vacante', 'pagina')),
  titulo text not null check (char_length(titulo) between 1 and 200),
  pais text,
  ciudad text,
  url text not null check (url ~ '^https://'),
  publicada_en date,
  cierra_en date,
  -- Tal como los publicó la aerolínea, uno por renglón.
  requisitos text[] not null default '{}',
  idioma text not null default 'es' check (idioma in ('es', 'en')),
  abierta boolean not null default true,
  fuente text not null check (fuente in ('automatica', 'manual')),
  vista_por_primera_vez timestamptz not null default now(),
  vista_por_ultima_vez timestamptz not null default now(),
  cerrada_en timestamptz,
  -- También es el índice de la clave foránea: airline_id va primero.
  unique (airline_id, clave_externa)
);

comment on table public.convocatorias is
  'Convocatorias de piloto de cada aerolínea. Las escribe la función revisar-convocatorias (y private.convocatoria_manual para LATAM); los pilotos solo las leen.';

alter table public.convocatorias enable row level security;

create policy "convocatorias: las lee cualquier piloto con sesión"
  on public.convocatorias for select to authenticated
  using (true);

grant select on table public.convocatorias to authenticated;

-- Cada corrida de la función: cuándo empezó (con eso se frena si la llaman
-- seguido), cuándo terminó y qué pasó con cada fuente. Sin políticas ni
-- permisos: la escribe la función con service_role y se lee desde el panel.
create table public.convocatorias_revisiones (
  id bigint generated by default as identity primary key,
  empezo_en timestamptz not null default now(),
  termino_en timestamptz,
  resultado jsonb not null default '{}'::jsonb
);

comment on table public.convocatorias_revisiones is
  'Una fila por corrida de revisar-convocatorias: qué leyó de cada aerolínea y qué falló.';

alter table public.convocatorias_revisiones enable row level security;

create index convocatorias_revisiones_empezo_en_idx on public.convocatorias_revisiones (empezo_en desc);

-- ─── A mano ─────────────────────────────────────────────────────────────────
-- Para LATAM, o para cualquier aerolínea cuyo portal deje de poder leerse.
-- Se corre desde el editor SQL de Supabase:
--
--   select private.convocatoria_manual(
--     'LAN', 'Primer oficial', 'https://…la vacante…', true,
--     array['Tener al menos 20 años de edad', '…'], 'Colombia');
--
-- y para cerrarla, lo mismo con `false`: los requisitos se conservan. La clave
-- (`p_clave`, por defecto 'manual') es la que identifica la fila: para tener
-- dos convocatorias de la misma aerolínea, cada una con la suya.
create or replace function private.convocatoria_manual(
  p_aerolinea text,
  p_titulo text,
  p_url text,
  p_abierta boolean,
  p_requisitos text[] default '{}',
  p_pais text default null,
  p_cargo text default 'primer_oficial',
  p_clave text default 'manual',
  p_tipo text default 'vacante'
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_airline bigint;
begin
  select id into v_airline from public.airlines where code = p_aerolinea;
  if v_airline is null then
    raise exception 'No hay una aerolínea con el código %', p_aerolinea using errcode = 'invalid_parameter_value';
  end if;

  insert into public.convocatorias as c
    (airline_id, clave_externa, cargo, tipo, titulo, pais, url, requisitos, abierta, fuente, cerrada_en)
  values
    (v_airline, p_clave, p_cargo, p_tipo, p_titulo, p_pais, p_url, coalesce(p_requisitos, '{}'), p_abierta, 'manual',
     case when p_abierta then null else now() end)
  on conflict (airline_id, clave_externa) do update set
    cargo = excluded.cargo,
    tipo = excluded.tipo,
    titulo = excluded.titulo,
    pais = coalesce(excluded.pais, c.pais),
    url = excluded.url,
    -- Cerrar sin repetir los requisitos no los borra.
    requisitos = case when cardinality(excluded.requisitos) > 0 then excluded.requisitos else c.requisitos end,
    abierta = excluded.abierta,
    fuente = 'manual',
    vista_por_ultima_vez = now(),
    cerrada_en = case when excluded.abierta then null else coalesce(c.cerrada_en, now()) end;
end;
$$;

revoke all on function private.convocatoria_manual(text, text, text, boolean, text[], text, text, text, text) from public, anon, authenticated;

comment on function private.convocatoria_manual(text, text, text, boolean, text[], text, text, text, text) is
  'Marca a mano una convocatoria (LATAM). Solo desde el editor SQL.';

-- La página de pilotos de LATAM, leída el 26-sep-2026 en
-- latamairlines.com/co/es/trabaja-con-nosotros/reclutamiento-y-seleccion/pilotos.
-- Sin convocatoria abierta ese día: queda como página, cerrada.
select private.convocatoria_manual(
  'LAN',
  'Primer oficial',
  'https://www.latamairlines.com/co/es/trabaja-con-nosotros/reclutamiento-y-seleccion/pilotos',
  false,
  array[
    'Tener al menos 20 años de edad',
    'Contar con Licencia de Piloto Comercial o PCA',
    'Haber acumulado 150 horas de vuelo o más',
    'Contar con Nivel de Inglés OACI 4 o Superior',
    'Contar con Apto Médico vigente',
    'Contar con habilitación IFR',
    'Contar con pasaporte con vigencia de al menos 6 meses',
    'Contar con Visa Americana B1/B2'
  ],
  'Colombia',
  'primer_oficial',
  'pagina-pilotos',
  'pagina'
);

-- ─── La agenda ──────────────────────────────────────────────────────────────
-- Cada 6 horas, a los 17 minutos (00:17, 06:17, 12:17 y 18:17 UTC). La función
-- no pide JWT y se frena sola si la llaman antes de 50 minutos.
do $agenda$
begin
  if exists (select 1 from cron.job where jobname = 'aviatory_convocatorias') then
    perform cron.unschedule('aviatory_convocatorias');
  end if;
  perform cron.schedule(
    'aviatory_convocatorias', '17 */6 * * *',
    $cron$select net.http_post(
      url := 'https://gvwqmfxphsbmbrhyjcmk.supabase.co/functions/v1/revisar-convocatorias',
      body := '{}'::jsonb,
      headers := '{"Content-Type": "application/json"}'::jsonb,
      timeout_milliseconds := 120000
    )$cron$
  );
end;
$agenda$;
